// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Segment Audience ID to which user identifier should be added or removed
   */
  segment_audience_id: string
  /**
   * Segment Audience key to which user identifier should be added or removed
   */
  segment_audience_key: string
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
   */
  segment_computation_action: string
  /**
   * The Segment userId value.
   */
  segment_user_id?: string
  /**
   * The Segment anonymousId value.
   */
  segment_anonymous_id?: string
  /**
   * A computed object for track and identify events. This field should not need to be edited.
   */
  traits_or_props: {
    [k: string]: unknown
  }
  /**
   * Indicates if the user will be added or removed from the Audience
   */
  audience_action?: string
}
