/**
 * Generated Types for Collab Travel CRM Destination
 * 
 * These types are auto-generated by Segment's tooling.
 * This file serves as a template for the structure.
 */

// Settings type - defines authentication fields
export interface Settings {
  /**
   * Your Collab Travel CRM webhook secret.
   */
  apiKey: string
}
