import type { ActionDefinition } from '@segment/actions-core'
import type { Settings } from '../generated-types'
import type { Payload } from './generated-types'
import { TopsortAPIClient } from '../client'

const action: ActionDefinition<Settings, Payload> = {
  title: 'ImpressionsList',
  defaultSubscription: 'type = "track" and event = "Product List Viewed"',
  description: 'Send impression events to Topsort when a consumer has viewed a list of promotables.',
  fields: {
    products: {
      label: 'Products',
      description: 'The list of products viewed. Each product is a promotable entity.',
      type: 'object',
      multiple: true,
      required: true,
      default: {
        '@path': '$.properties.products'
      }
    },
    id: {
      label: 'Event ID',
      description:
        'Unique ID generated by the client to suppress duplicate events. The length should not exceed 128 characters.',
      type: 'string',
      required: true,
      default: {
        '@path': '$.messageId'
      }
    },
    occurredAt: {
      label: 'Occurred At',
      description: 'Timestamp that the event happened at.',
      type: 'datetime',
      required: true,
      default: {
        '@path': '$.timestamp'
      }
    },
    opaqueUserId: {
      label: 'Opaque User ID',
      description:
        'Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.',
      type: 'string',
      required: true,
      default: {
        '@path': '$.anonymousId'
      }
    }
  },
  perform: (request, { payload, settings }) => {
    const client = new TopsortAPIClient(request, settings)
    const impressions = payload.products?.map((product: Record<string, unknown>) => {
      const impression: any = {
        ...product,
        id: payload.id,
        occurredAt: payload.occurredAt,
        opaqueUserId: payload.opaqueUserId,
        resolvedBidId: product.resolvedBidId
      }
      if (product.additionalAttribution) {
        impression.additionalAttribution = product.additionalAttribution
      }
      return impression
    })
    return client.sendEvent({
      impressions
    })
  }
}

export default action
