// Generated file. DO NOT MODIFY IT BY HAND.

export interface Settings {
  /**
   * Base URL for the Memora API.
   */
  url: string
  /**
   * A unique Profile Service ID using Twilio Type ID (TTID) format (e.g., mem_service_00000000000000000000000000)
   */
  serviceId: string
  /**
   * Bearer token for authentication. Generated by the Twilio Rest Proxy service.
   */
  api_key: string
  /**
   * Twilio Account ID for X-Pre-Auth-Context header (optional)
   */
  twilioAccount?: string
}
