// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * An identifier for the Floodlight activity group associated with this activity, which appears as a parameter in your tags. This value is case sensitive.
   */
  activityGroupTagString: string
  /**
   * An identifier for your Floodlight activity, which appears as a parameter in your tags. This value is case sensitive.
   */
  activityTagString: string
  /**
   * In Campaign Manager, go to Floodlight -> Configuration, under Tags, if **Dynamic** is selected, select **True**
   */
  enableDynamicTags?: boolean
  /**
   * Specifies how conversions will be counted for this Floodlight activity.
   */
  countingMethod: string
  /**
   * Use this field to insert a unique numerical identifier for each transaction.  Can be alphanumeric.
   */
  transactionId: string
  /**
   * Use this field to pass the revenue generated by a transaction. Typically the purchase price and value does not include taxes or shipping.
   */
  value: string
  /**
   *
   *       Use this field to pass the number of items sold during a transaction:
   *       - If you're counting each transaction as a single conversion, the value is 1.
   *       - If you're counting each item sold during a single transaction as a separate conversion, insert the number of items sold as part of each transaction as the value.
   *       - The value must be an integer greater than zero.
   *
   */
  quantity: number
  /**
   * Custom Floodlight variables enable you to capture information beyond the basics (visits and revenue) that you can collect with standard parameters in your tags.
   */
  uVariables?: {
    [k: string]: unknown
  }
  /**
   * You can insert custom data into event snippets with the dc_custom_params field. This field accepts any values you want to pass to Google Marketing Platform.
   */
  dcCustomParams?: {
    [k: string]: unknown
  }
}
