export const CREATE_AUDIENCE_URL = 'https://graph.facebook.com/v24.0/act_<AD_ACCOUNT_ID>/customaudiences'
export const GET_AUDIENCE_URL = 'https://graph.facebook.com/${API_VERSION}/${externalId}'

export const US_STATE_CODES = new Map<string, string>([
  ['arizona', 'az'],
  ['alabama', 'al'],
  ['alaska', 'ak'],
  ['arkansas', 'ar'],
  ['california', 'ca'],
  ['colorado', 'co'],
  ['connecticut', 'ct'],
  ['delaware', 'de'],
  ['florida', 'fl'],
  ['georgia', 'ga'],
  ['hawaii', 'hi'],
  ['idaho', 'id'],
  ['illinois', 'il'],
  ['indiana', 'in'],
  ['iowa', 'ia'],
  ['kansas', 'ks'],
  ['kentucky', 'ky'],
  ['louisiana', 'la'],
  ['maine', 'me'],
  ['maryland', 'md'],
  ['massachusetts', 'ma'],
  ['michigan', 'mi'],
  ['minnesota', 'mn'],
  ['mississippi', 'ms'],
  ['missouri', 'mo'],
  ['montana', 'mt'],
  ['nebraska', 'ne'],
  ['nevada', 'nv'],
  ['newhampshire', 'nh'],
  ['newjersey', 'nj'],
  ['newmexico', 'nm'],
  ['newyork', 'ny'],
  ['northcarolina', 'nc'],
  ['northdakota', 'nd'],
  ['ohio', 'oh'],
  ['oklahoma', 'ok'],
  ['oregon', 'or'],
  ['pennsylvania', 'pa'],
  ['rhodeisland', 'ri'],
  ['southcarolina', 'sc'],
  ['southdakota', 'sd'],
  ['tennessee', 'tn'],
  ['texas', 'tx'],
  ['utah', 'ut'],
  ['vermont', 'vt'],
  ['virginia', 'va'],
  ['washington', 'wa'],
  ['westvirginia', 'wv'],
  ['wisconsin', 'wi'],
  ['wyoming', 'wy']
])
export const API_VERSION = 'v24.0'
export const BASE_URL = 'https://graph.facebook.com'
export const FACEBOOK_CUSTOM_AUDIENCE_FLAGON = 'facebook-custom-audience-actions-canary-version'
