// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Column names to write to S3 CSV file.
   */
  columns: {
    /**
     * Name of column for the Audience Name
     */
    audience_name?: string
    /**
     * Name of column for the Audience ID
     */
    audience_id?: string
    /**
     * Indicates if the user has been added or removed from the Audience. true = added, false = removed.
     */
    audience_action?: string
    /**
     * Name of column for email address
     */
    email?: string
    /**
     * Name of column for user ID
     */
    user_id?: string
    /**
     * Name of column for anonymous ID
     */
    anonymous_id?: string
    /**
     * Name of column for timestamp for when the user was added or removed from the Audience
     */
    timestamp?: string
    /**
     * Name of column for the unique identifier for the message.
     */
    message_id?: string
    /**
     * Name of column for the unique identifier for the Segment Engage Space that generated the event.
     */
    space_id?: string
    /**
     * Name of column for the Integration Object. This contains JSON details of which destinations the event was synced to by Segment
     */
    integrations_object?: string
    /**
     * Name of column for properties and traits. This data contains the entire properties object from a track() call or the traits object from an identify() call emitted from Engage when a user is added to or removed from an Audience
     */
    properties_or_traits?: string
  }
  /**
   * Audience Name Hidden Field
   */
  audienceName: string
  /**
   * Audience ID Hidden Field
   */
  audienceId: string
  /**
   * Email Hidden Field
   */
  email?: string
  /**
   * User ID Hidden Field
   */
  userId?: string
  /**
   * Anonymous ID Hidden Field
   */
  anonymousId?: string
  /**
   * Timestamp Hidden Field
   */
  timestamp: string | number
  /**
   * Message ID Hidden Field
   */
  messageId: string
  /**
   * Space ID Hidden Field
   */
  spaceId: string
  /**
   * Integrations Object Hidden Field
   */
  integrationsObject: {
    [k: string]: unknown
  }
  /**
   * Properties or Traits Hidden Field
   */
  propertiesOrTraits: {
    [k: string]: unknown
  }
  /**
   * Additional user identifiers and traits to include as separate columns in the CSV file. Each item should contain a key and a value. The key is the trait or identifier name from the payload, and the value is the column name to be written to the CSV file.
   */
  additional_identifiers_and_traits_columns?: {
    [k: string]: unknown
  }
  /**
   * Receive events in a batch payload. This is required for LiveRamp audiences ingestion.
   */
  enable_batching: boolean
  /**
   * Maximum number of events to include in each batch. Actual batch sizes may be lower.
   */
  batch_size?: number
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' will be dropped before the perform() fuction call.
   */
  computation_class: string
}
