export const CONSENT_STATUS_GRANTED = 'CONSENT_STATUS_GRANTED'
export const CONSENT_STATUS_DENIED = 'CONSENT_STATUS_DENIED'
export const CONTACT_INFO = 'CUSTOMER_MATCH_CONTACT_INFO'
export const DEVICE_ID = 'CUSTOMER_MATCH_DEVICE_ID'
