export const CONSENT_STATUS_GRANTED = 'CONSENT_STATUS_GRANTED' as const
export const CONSENT_STATUS_DENIED = 'CONSENT_STATUS_DENIED' as const
export const CONTACT_INFO = 'CUSTOMER_MATCH_CONTACT_INFO' as const
export const DEVICE_ID = 'CUSTOMER_MATCH_DEVICE_ID' as const
