export const CONSENT_STATUS_GRANTED = 'CONSENT_STATUS_GRANTED' as const
export const CONSENT_STATUS_DENIED = 'CONSENT_STATUS_DENIED' as const
export const CONTACT_INFO = 'CUSTOMER_MATCH_CONTACT_INFO' as const
export const DEVICE_ID = 'CUSTOMER_MATCH_DEVICE_ID' as const

// Four different fields are labelled Audience Type: the mapping field, the audience setting,
// and the hook's input and output. Error messages have to say which one they mean, so the
// labels live here and are used both to define the fields and to talk about them.
export const AUDIENCE_TYPE_LABEL = 'Audience Type'
export const RETL_HOOK_LABEL = 'Select or create an audience in Display & Video 360'

export const PHONE_NORMALIZATION_NONE = 'none' as const
export const PHONE_NORMALIZATION_NORMALIZE = 'normalize' as const
export const PHONE_NORMALIZATION_VALIDATE = 'normalize_and_validate' as const

// The 245 regions google-libphonenumber has metadata for, so a country picked here is always one
// it can parse a national-format number against. The code is the ISO 3166-1 alpha-2 code, which
// is also what Display & Video 360 expects for a contact info member's countryCode. PS is named
// Palestine rather than the Palestinian Territories which the generated names give.
export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', dialing: 93 },
  { name: 'Åland Islands', code: 'AX', dialing: 358 },
  { name: 'Albania', code: 'AL', dialing: 355 },
  { name: 'Algeria', code: 'DZ', dialing: 213 },
  { name: 'American Samoa', code: 'AS', dialing: 1 },
  { name: 'Andorra', code: 'AD', dialing: 376 },
  { name: 'Angola', code: 'AO', dialing: 244 },
  { name: 'Anguilla', code: 'AI', dialing: 1 },
  { name: 'Antigua & Barbuda', code: 'AG', dialing: 1 },
  { name: 'Argentina', code: 'AR', dialing: 54 },
  { name: 'Armenia', code: 'AM', dialing: 374 },
  { name: 'Aruba', code: 'AW', dialing: 297 },
  { name: 'Ascension Island', code: 'AC', dialing: 247 },
  { name: 'Australia', code: 'AU', dialing: 61 },
  { name: 'Austria', code: 'AT', dialing: 43 },
  { name: 'Azerbaijan', code: 'AZ', dialing: 994 },
  { name: 'Bahamas', code: 'BS', dialing: 1 },
  { name: 'Bahrain', code: 'BH', dialing: 973 },
  { name: 'Bangladesh', code: 'BD', dialing: 880 },
  { name: 'Barbados', code: 'BB', dialing: 1 },
  { name: 'Belarus', code: 'BY', dialing: 375 },
  { name: 'Belgium', code: 'BE', dialing: 32 },
  { name: 'Belize', code: 'BZ', dialing: 501 },
  { name: 'Benin', code: 'BJ', dialing: 229 },
  { name: 'Bermuda', code: 'BM', dialing: 1 },
  { name: 'Bhutan', code: 'BT', dialing: 975 },
  { name: 'Bolivia', code: 'BO', dialing: 591 },
  { name: 'Bosnia & Herzegovina', code: 'BA', dialing: 387 },
  { name: 'Botswana', code: 'BW', dialing: 267 },
  { name: 'Brazil', code: 'BR', dialing: 55 },
  { name: 'British Indian Ocean Territory', code: 'IO', dialing: 246 },
  { name: 'British Virgin Islands', code: 'VG', dialing: 1 },
  { name: 'Brunei', code: 'BN', dialing: 673 },
  { name: 'Bulgaria', code: 'BG', dialing: 359 },
  { name: 'Burkina Faso', code: 'BF', dialing: 226 },
  { name: 'Burundi', code: 'BI', dialing: 257 },
  { name: 'Cambodia', code: 'KH', dialing: 855 },
  { name: 'Cameroon', code: 'CM', dialing: 237 },
  { name: 'Canada', code: 'CA', dialing: 1 },
  { name: 'Cape Verde', code: 'CV', dialing: 238 },
  { name: 'Caribbean Netherlands', code: 'BQ', dialing: 599 },
  { name: 'Cayman Islands', code: 'KY', dialing: 1 },
  { name: 'Central African Republic', code: 'CF', dialing: 236 },
  { name: 'Chad', code: 'TD', dialing: 235 },
  { name: 'Chile', code: 'CL', dialing: 56 },
  { name: 'China', code: 'CN', dialing: 86 },
  { name: 'Christmas Island', code: 'CX', dialing: 61 },
  { name: 'Cocos (Keeling) Islands', code: 'CC', dialing: 61 },
  { name: 'Colombia', code: 'CO', dialing: 57 },
  { name: 'Comoros', code: 'KM', dialing: 269 },
  { name: 'Congo - Brazzaville', code: 'CG', dialing: 242 },
  { name: 'Congo - Kinshasa', code: 'CD', dialing: 243 },
  { name: 'Cook Islands', code: 'CK', dialing: 682 },
  { name: 'Costa Rica', code: 'CR', dialing: 506 },
  { name: 'Côte d’Ivoire', code: 'CI', dialing: 225 },
  { name: 'Croatia', code: 'HR', dialing: 385 },
  { name: 'Cuba', code: 'CU', dialing: 53 },
  { name: 'Curaçao', code: 'CW', dialing: 599 },
  { name: 'Cyprus', code: 'CY', dialing: 357 },
  { name: 'Czechia', code: 'CZ', dialing: 420 },
  { name: 'Denmark', code: 'DK', dialing: 45 },
  { name: 'Djibouti', code: 'DJ', dialing: 253 },
  { name: 'Dominica', code: 'DM', dialing: 1 },
  { name: 'Dominican Republic', code: 'DO', dialing: 1 },
  { name: 'Ecuador', code: 'EC', dialing: 593 },
  { name: 'Egypt', code: 'EG', dialing: 20 },
  { name: 'El Salvador', code: 'SV', dialing: 503 },
  { name: 'Equatorial Guinea', code: 'GQ', dialing: 240 },
  { name: 'Eritrea', code: 'ER', dialing: 291 },
  { name: 'Estonia', code: 'EE', dialing: 372 },
  { name: 'Eswatini', code: 'SZ', dialing: 268 },
  { name: 'Ethiopia', code: 'ET', dialing: 251 },
  { name: 'Falkland Islands', code: 'FK', dialing: 500 },
  { name: 'Faroe Islands', code: 'FO', dialing: 298 },
  { name: 'Fiji', code: 'FJ', dialing: 679 },
  { name: 'Finland', code: 'FI', dialing: 358 },
  { name: 'France', code: 'FR', dialing: 33 },
  { name: 'French Guiana', code: 'GF', dialing: 594 },
  { name: 'French Polynesia', code: 'PF', dialing: 689 },
  { name: 'Gabon', code: 'GA', dialing: 241 },
  { name: 'Gambia', code: 'GM', dialing: 220 },
  { name: 'Georgia', code: 'GE', dialing: 995 },
  { name: 'Germany', code: 'DE', dialing: 49 },
  { name: 'Ghana', code: 'GH', dialing: 233 },
  { name: 'Gibraltar', code: 'GI', dialing: 350 },
  { name: 'Greece', code: 'GR', dialing: 30 },
  { name: 'Greenland', code: 'GL', dialing: 299 },
  { name: 'Grenada', code: 'GD', dialing: 1 },
  { name: 'Guadeloupe', code: 'GP', dialing: 590 },
  { name: 'Guam', code: 'GU', dialing: 1 },
  { name: 'Guatemala', code: 'GT', dialing: 502 },
  { name: 'Guernsey', code: 'GG', dialing: 44 },
  { name: 'Guinea', code: 'GN', dialing: 224 },
  { name: 'Guinea-Bissau', code: 'GW', dialing: 245 },
  { name: 'Guyana', code: 'GY', dialing: 592 },
  { name: 'Haiti', code: 'HT', dialing: 509 },
  { name: 'Honduras', code: 'HN', dialing: 504 },
  { name: 'Hong Kong SAR China', code: 'HK', dialing: 852 },
  { name: 'Hungary', code: 'HU', dialing: 36 },
  { name: 'Iceland', code: 'IS', dialing: 354 },
  { name: 'India', code: 'IN', dialing: 91 },
  { name: 'Indonesia', code: 'ID', dialing: 62 },
  { name: 'Iran', code: 'IR', dialing: 98 },
  { name: 'Iraq', code: 'IQ', dialing: 964 },
  { name: 'Ireland', code: 'IE', dialing: 353 },
  { name: 'Isle of Man', code: 'IM', dialing: 44 },
  { name: 'Israel', code: 'IL', dialing: 972 },
  { name: 'Italy', code: 'IT', dialing: 39 },
  { name: 'Jamaica', code: 'JM', dialing: 1 },
  { name: 'Japan', code: 'JP', dialing: 81 },
  { name: 'Jersey', code: 'JE', dialing: 44 },
  { name: 'Jordan', code: 'JO', dialing: 962 },
  { name: 'Kazakhstan', code: 'KZ', dialing: 7 },
  { name: 'Kenya', code: 'KE', dialing: 254 },
  { name: 'Kiribati', code: 'KI', dialing: 686 },
  { name: 'Kosovo', code: 'XK', dialing: 383 },
  { name: 'Kuwait', code: 'KW', dialing: 965 },
  { name: 'Kyrgyzstan', code: 'KG', dialing: 996 },
  { name: 'Laos', code: 'LA', dialing: 856 },
  { name: 'Latvia', code: 'LV', dialing: 371 },
  { name: 'Lebanon', code: 'LB', dialing: 961 },
  { name: 'Lesotho', code: 'LS', dialing: 266 },
  { name: 'Liberia', code: 'LR', dialing: 231 },
  { name: 'Libya', code: 'LY', dialing: 218 },
  { name: 'Liechtenstein', code: 'LI', dialing: 423 },
  { name: 'Lithuania', code: 'LT', dialing: 370 },
  { name: 'Luxembourg', code: 'LU', dialing: 352 },
  { name: 'Macao SAR China', code: 'MO', dialing: 853 },
  { name: 'Madagascar', code: 'MG', dialing: 261 },
  { name: 'Malawi', code: 'MW', dialing: 265 },
  { name: 'Malaysia', code: 'MY', dialing: 60 },
  { name: 'Maldives', code: 'MV', dialing: 960 },
  { name: 'Mali', code: 'ML', dialing: 223 },
  { name: 'Malta', code: 'MT', dialing: 356 },
  { name: 'Marshall Islands', code: 'MH', dialing: 692 },
  { name: 'Martinique', code: 'MQ', dialing: 596 },
  { name: 'Mauritania', code: 'MR', dialing: 222 },
  { name: 'Mauritius', code: 'MU', dialing: 230 },
  { name: 'Mayotte', code: 'YT', dialing: 262 },
  { name: 'Mexico', code: 'MX', dialing: 52 },
  { name: 'Micronesia', code: 'FM', dialing: 691 },
  { name: 'Moldova', code: 'MD', dialing: 373 },
  { name: 'Monaco', code: 'MC', dialing: 377 },
  { name: 'Mongolia', code: 'MN', dialing: 976 },
  { name: 'Montenegro', code: 'ME', dialing: 382 },
  { name: 'Montserrat', code: 'MS', dialing: 1 },
  { name: 'Morocco', code: 'MA', dialing: 212 },
  { name: 'Mozambique', code: 'MZ', dialing: 258 },
  { name: 'Myanmar (Burma)', code: 'MM', dialing: 95 },
  { name: 'Namibia', code: 'NA', dialing: 264 },
  { name: 'Nauru', code: 'NR', dialing: 674 },
  { name: 'Nepal', code: 'NP', dialing: 977 },
  { name: 'Netherlands', code: 'NL', dialing: 31 },
  { name: 'New Caledonia', code: 'NC', dialing: 687 },
  { name: 'New Zealand', code: 'NZ', dialing: 64 },
  { name: 'Nicaragua', code: 'NI', dialing: 505 },
  { name: 'Niger', code: 'NE', dialing: 227 },
  { name: 'Nigeria', code: 'NG', dialing: 234 },
  { name: 'Niue', code: 'NU', dialing: 683 },
  { name: 'Norfolk Island', code: 'NF', dialing: 672 },
  { name: 'North Korea', code: 'KP', dialing: 850 },
  { name: 'North Macedonia', code: 'MK', dialing: 389 },
  { name: 'Northern Mariana Islands', code: 'MP', dialing: 1 },
  { name: 'Norway', code: 'NO', dialing: 47 },
  { name: 'Oman', code: 'OM', dialing: 968 },
  { name: 'Pakistan', code: 'PK', dialing: 92 },
  { name: 'Palau', code: 'PW', dialing: 680 },
  { name: 'Palestine', code: 'PS', dialing: 970 },
  { name: 'Panama', code: 'PA', dialing: 507 },
  { name: 'Papua New Guinea', code: 'PG', dialing: 675 },
  { name: 'Paraguay', code: 'PY', dialing: 595 },
  { name: 'Peru', code: 'PE', dialing: 51 },
  { name: 'Philippines', code: 'PH', dialing: 63 },
  { name: 'Poland', code: 'PL', dialing: 48 },
  { name: 'Portugal', code: 'PT', dialing: 351 },
  { name: 'Puerto Rico', code: 'PR', dialing: 1 },
  { name: 'Qatar', code: 'QA', dialing: 974 },
  { name: 'Réunion', code: 'RE', dialing: 262 },
  { name: 'Romania', code: 'RO', dialing: 40 },
  { name: 'Russia', code: 'RU', dialing: 7 },
  { name: 'Rwanda', code: 'RW', dialing: 250 },
  { name: 'Samoa', code: 'WS', dialing: 685 },
  { name: 'San Marino', code: 'SM', dialing: 378 },
  { name: 'São Tomé & Príncipe', code: 'ST', dialing: 239 },
  { name: 'Saudi Arabia', code: 'SA', dialing: 966 },
  { name: 'Senegal', code: 'SN', dialing: 221 },
  { name: 'Serbia', code: 'RS', dialing: 381 },
  { name: 'Seychelles', code: 'SC', dialing: 248 },
  { name: 'Sierra Leone', code: 'SL', dialing: 232 },
  { name: 'Singapore', code: 'SG', dialing: 65 },
  { name: 'Sint Maarten', code: 'SX', dialing: 1 },
  { name: 'Slovakia', code: 'SK', dialing: 421 },
  { name: 'Slovenia', code: 'SI', dialing: 386 },
  { name: 'Solomon Islands', code: 'SB', dialing: 677 },
  { name: 'Somalia', code: 'SO', dialing: 252 },
  { name: 'South Africa', code: 'ZA', dialing: 27 },
  { name: 'South Korea', code: 'KR', dialing: 82 },
  { name: 'South Sudan', code: 'SS', dialing: 211 },
  { name: 'Spain', code: 'ES', dialing: 34 },
  { name: 'Sri Lanka', code: 'LK', dialing: 94 },
  { name: 'St. Barthélemy', code: 'BL', dialing: 590 },
  { name: 'St. Helena', code: 'SH', dialing: 290 },
  { name: 'St. Kitts & Nevis', code: 'KN', dialing: 1 },
  { name: 'St. Lucia', code: 'LC', dialing: 1 },
  { name: 'St. Martin', code: 'MF', dialing: 590 },
  { name: 'St. Pierre & Miquelon', code: 'PM', dialing: 508 },
  { name: 'St. Vincent & Grenadines', code: 'VC', dialing: 1 },
  { name: 'Sudan', code: 'SD', dialing: 249 },
  { name: 'Suriname', code: 'SR', dialing: 597 },
  { name: 'Svalbard & Jan Mayen', code: 'SJ', dialing: 47 },
  { name: 'Sweden', code: 'SE', dialing: 46 },
  { name: 'Switzerland', code: 'CH', dialing: 41 },
  { name: 'Syria', code: 'SY', dialing: 963 },
  { name: 'Taiwan', code: 'TW', dialing: 886 },
  { name: 'Tajikistan', code: 'TJ', dialing: 992 },
  { name: 'Tanzania', code: 'TZ', dialing: 255 },
  { name: 'Thailand', code: 'TH', dialing: 66 },
  { name: 'Timor-Leste', code: 'TL', dialing: 670 },
  { name: 'Togo', code: 'TG', dialing: 228 },
  { name: 'Tokelau', code: 'TK', dialing: 690 },
  { name: 'Tonga', code: 'TO', dialing: 676 },
  { name: 'Trinidad & Tobago', code: 'TT', dialing: 1 },
  { name: 'Tristan da Cunha', code: 'TA', dialing: 290 },
  { name: 'Tunisia', code: 'TN', dialing: 216 },
  { name: 'Türkiye', code: 'TR', dialing: 90 },
  { name: 'Turkmenistan', code: 'TM', dialing: 993 },
  { name: 'Turks & Caicos Islands', code: 'TC', dialing: 1 },
  { name: 'Tuvalu', code: 'TV', dialing: 688 },
  { name: 'U.S. Virgin Islands', code: 'VI', dialing: 1 },
  { name: 'Uganda', code: 'UG', dialing: 256 },
  { name: 'Ukraine', code: 'UA', dialing: 380 },
  { name: 'United Arab Emirates', code: 'AE', dialing: 971 },
  { name: 'United Kingdom', code: 'GB', dialing: 44 },
  { name: 'United States', code: 'US', dialing: 1 },
  { name: 'Uruguay', code: 'UY', dialing: 598 },
  { name: 'Uzbekistan', code: 'UZ', dialing: 998 },
  { name: 'Vanuatu', code: 'VU', dialing: 678 },
  { name: 'Vatican City', code: 'VA', dialing: 39 },
  { name: 'Venezuela', code: 'VE', dialing: 58 },
  { name: 'Vietnam', code: 'VN', dialing: 84 },
  { name: 'Wallis & Futuna', code: 'WF', dialing: 681 },
  { name: 'Western Sahara', code: 'EH', dialing: 212 },
  { name: 'Yemen', code: 'YE', dialing: 967 },
  { name: 'Zambia', code: 'ZM', dialing: 260 },
  { name: 'Zimbabwe', code: 'ZW', dialing: 263 }
] as const

export const COUNTRY_CHOICES = COUNTRIES.map(({ name, code, dialing }) => ({
  label: `${name} (${code}, +${dialing})`,
  value: code
}))
