// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * The type of Segment call. One of: track, page, screen, identify.
   */
  type: string
  /**
   * Name of the event. Present on track calls only, limited to 1024 characters. Page and screen calls are sent as "Page viewed" and "Screen viewed".
   */
  event?: string
  /**
   * Name of the page or screen being viewed. Present on page and screen calls only.
   */
  name?: string
  /**
   * A string that uniquely identifies a user, such as an email, handle, or username. No two users in one environment may share the same identity. Defaults to the Segment userId.
   */
  identity?: string
  /**
   * The Segment anonymous ID for the user.
   */
  anonymous_id?: string
  /**
   * Heap’s own internal numeric user ID (a numeric string between 0 and 2^53). This is not a Segment userId — map the Segment userId to Identity instead.
   */
  user_id?: string | null
  /**
   * The user’s email address, sent as an additional Heap identifier.
   */
  email?: string
  /**
   * An object with key-value properties to associate with the event. Nested objects are flattened and all values are sent to Heap as strings.
   */
  properties?: {
    [k: string]: unknown
  }
  /**
   * An object with key-value properties to associate with the user profile. Must be sent with an identity identifier.
   */
  traits?: {
    [k: string]: unknown
  }
  /**
   * The timestamp of the event. Defaults to the current time if not provided.
   */
  timestamp?: string | number
  /**
   * Unique event ID generated by Segment, used as the Heap idempotency key.
   */
  message_id: string
}
