export const ORGANIZATION_URN_PREFIX = 'urn:li:organization:'

export const LINKEDIN_PROTOCOL_VERSION = '2.0.0'

export const SEGMENT_TYPES = {
  USER: 'USER',
  COMPANY: 'COMPANY'
} as const

export const AUDIENCE_ACTION = {
  ADD: 'ADD',
  REMOVE: 'REMOVE'
} as const

export const AUDIENCE_SOURCE = {
  ENGAGE_RETL: 'ENGAGE_RETL',
  CONNECTIONS: 'CONNECTIONS'
} as const

// 409 (conflict) is treated as retryable: it can occur when two concurrent syncs both miss the
// cache and attempt to create the same segment. Retrying resolves to the now-existing segment.
export const RETRYABLE_STATUSES: readonly number[] = [408, 409, 423, 429, 500, 502, 503, 504]

// Limits from LinkedIn's DMP Segment Companies schema. A value breaching one of these is dropped
// rather than truncated: a truncated city is a wrong city, and as a match signal that is worse
// than no signal at all.
export const MAX_COMPANY_PAGE_URL_LENGTH = 100
export const MAX_INDUSTRY_LENGTH = 50
export const MAX_INDUSTRIES = 3
export const MAX_CITY_LENGTH = 50
export const MAX_STATE_LENGTH = 50
export const MAX_POSTAL_CODE_LENGTH = 20
export const MAX_STOCK_SYMBOL_LENGTH = 5

/**
 * ISO 3166-1 alpha-2 country codes. LinkedIn's DMP Segment Companies API requires the
 * two-letter code for a company's `country`.
 */
export const COUNTRY_CHOICES: ReadonlyArray<{ label: string; value: string }> = [
  { label: 'Afghanistan (AF)', value: 'AF' },
  { label: 'Åland Islands (AX)', value: 'AX' },
  { label: 'Albania (AL)', value: 'AL' },
  { label: 'Algeria (DZ)', value: 'DZ' },
  { label: 'American Samoa (AS)', value: 'AS' },
  { label: 'Andorra (AD)', value: 'AD' },
  { label: 'Angola (AO)', value: 'AO' },
  { label: 'Anguilla (AI)', value: 'AI' },
  { label: 'Antarctica (AQ)', value: 'AQ' },
  { label: 'Antigua and Barbuda (AG)', value: 'AG' },
  { label: 'Argentina (AR)', value: 'AR' },
  { label: 'Armenia (AM)', value: 'AM' },
  { label: 'Aruba (AW)', value: 'AW' },
  { label: 'Australia (AU)', value: 'AU' },
  { label: 'Austria (AT)', value: 'AT' },
  { label: 'Azerbaijan (AZ)', value: 'AZ' },
  { label: 'Bahamas (BS)', value: 'BS' },
  { label: 'Bahrain (BH)', value: 'BH' },
  { label: 'Bangladesh (BD)', value: 'BD' },
  { label: 'Barbados (BB)', value: 'BB' },
  { label: 'Belarus (BY)', value: 'BY' },
  { label: 'Belgium (BE)', value: 'BE' },
  { label: 'Belize (BZ)', value: 'BZ' },
  { label: 'Benin (BJ)', value: 'BJ' },
  { label: 'Bermuda (BM)', value: 'BM' },
  { label: 'Bhutan (BT)', value: 'BT' },
  { label: 'Bolivia (Plurinational State of) (BO)', value: 'BO' },
  { label: 'Bonaire, Sint Eustatius and Saba (BQ)', value: 'BQ' },
  { label: 'Bosnia and Herzegovina (BA)', value: 'BA' },
  { label: 'Botswana (BW)', value: 'BW' },
  { label: 'Bouvet Island (BV)', value: 'BV' },
  { label: 'Brazil (BR)', value: 'BR' },
  { label: 'British Indian Ocean Territory (IO)', value: 'IO' },
  { label: 'Brunei Darussalam (BN)', value: 'BN' },
  { label: 'Bulgaria (BG)', value: 'BG' },
  { label: 'Burkina Faso (BF)', value: 'BF' },
  { label: 'Burundi (BI)', value: 'BI' },
  { label: 'Cabo Verde (CV)', value: 'CV' },
  { label: 'Cambodia (KH)', value: 'KH' },
  { label: 'Cameroon (CM)', value: 'CM' },
  { label: 'Canada (CA)', value: 'CA' },
  { label: 'Cayman Islands (KY)', value: 'KY' },
  { label: 'Central African Republic (CF)', value: 'CF' },
  { label: 'Chad (TD)', value: 'TD' },
  { label: 'Chile (CL)', value: 'CL' },
  { label: 'China (CN)', value: 'CN' },
  { label: 'Christmas Island (CX)', value: 'CX' },
  { label: 'Cocos (Keeling) Islands (CC)', value: 'CC' },
  { label: 'Colombia (CO)', value: 'CO' },
  { label: 'Comoros (KM)', value: 'KM' },
  { label: 'Congo (CG)', value: 'CG' },
  { label: 'Congo, Democratic Republic of the (CD)', value: 'CD' },
  { label: 'Cook Islands (CK)', value: 'CK' },
  { label: 'Costa Rica (CR)', value: 'CR' },
  { label: "Côte d'Ivoire (CI)", value: 'CI' },
  { label: 'Croatia (HR)', value: 'HR' },
  { label: 'Cuba (CU)', value: 'CU' },
  { label: 'Curaçao (CW)', value: 'CW' },
  { label: 'Cyprus (CY)', value: 'CY' },
  { label: 'Czechia (CZ)', value: 'CZ' },
  { label: 'Denmark (DK)', value: 'DK' },
  { label: 'Djibouti (DJ)', value: 'DJ' },
  { label: 'Dominica (DM)', value: 'DM' },
  { label: 'Dominican Republic (DO)', value: 'DO' },
  { label: 'Ecuador (EC)', value: 'EC' },
  { label: 'Egypt (EG)', value: 'EG' },
  { label: 'El Salvador (SV)', value: 'SV' },
  { label: 'Equatorial Guinea (GQ)', value: 'GQ' },
  { label: 'Eritrea (ER)', value: 'ER' },
  { label: 'Estonia (EE)', value: 'EE' },
  { label: 'Eswatini (SZ)', value: 'SZ' },
  { label: 'Ethiopia (ET)', value: 'ET' },
  { label: 'Falkland Islands (Malvinas) (FK)', value: 'FK' },
  { label: 'Faroe Islands (FO)', value: 'FO' },
  { label: 'Fiji (FJ)', value: 'FJ' },
  { label: 'Finland (FI)', value: 'FI' },
  { label: 'France (FR)', value: 'FR' },
  { label: 'French Guiana (GF)', value: 'GF' },
  { label: 'French Polynesia (PF)', value: 'PF' },
  { label: 'French Southern Territories (TF)', value: 'TF' },
  { label: 'Gabon (GA)', value: 'GA' },
  { label: 'Gambia (GM)', value: 'GM' },
  { label: 'Georgia (GE)', value: 'GE' },
  { label: 'Germany (DE)', value: 'DE' },
  { label: 'Ghana (GH)', value: 'GH' },
  { label: 'Gibraltar (GI)', value: 'GI' },
  { label: 'Greece (GR)', value: 'GR' },
  { label: 'Greenland (GL)', value: 'GL' },
  { label: 'Grenada (GD)', value: 'GD' },
  { label: 'Guadeloupe (GP)', value: 'GP' },
  { label: 'Guam (GU)', value: 'GU' },
  { label: 'Guatemala (GT)', value: 'GT' },
  { label: 'Guernsey (GG)', value: 'GG' },
  { label: 'Guinea (GN)', value: 'GN' },
  { label: 'Guinea-Bissau (GW)', value: 'GW' },
  { label: 'Guyana (GY)', value: 'GY' },
  { label: 'Haiti (HT)', value: 'HT' },
  { label: 'Heard Island and McDonald Islands (HM)', value: 'HM' },
  { label: 'Holy See (VA)', value: 'VA' },
  { label: 'Honduras (HN)', value: 'HN' },
  { label: 'Hong Kong (HK)', value: 'HK' },
  { label: 'Hungary (HU)', value: 'HU' },
  { label: 'Iceland (IS)', value: 'IS' },
  { label: 'India (IN)', value: 'IN' },
  { label: 'Indonesia (ID)', value: 'ID' },
  { label: 'Iran (Islamic Republic of) (IR)', value: 'IR' },
  { label: 'Iraq (IQ)', value: 'IQ' },
  { label: 'Ireland (IE)', value: 'IE' },
  { label: 'Isle of Man (IM)', value: 'IM' },
  { label: 'Israel (IL)', value: 'IL' },
  { label: 'Italy (IT)', value: 'IT' },
  { label: 'Jamaica (JM)', value: 'JM' },
  { label: 'Japan (JP)', value: 'JP' },
  { label: 'Jersey (JE)', value: 'JE' },
  { label: 'Jordan (JO)', value: 'JO' },
  { label: 'Kazakhstan (KZ)', value: 'KZ' },
  { label: 'Kenya (KE)', value: 'KE' },
  { label: 'Kiribati (KI)', value: 'KI' },
  { label: "Korea (Democratic People's Republic of) (KP)", value: 'KP' },
  { label: 'Korea, Republic of (KR)', value: 'KR' },
  { label: 'Kuwait (KW)', value: 'KW' },
  { label: 'Kyrgyzstan (KG)', value: 'KG' },
  { label: "Lao People's Democratic Republic (LA)", value: 'LA' },
  { label: 'Latvia (LV)', value: 'LV' },
  { label: 'Lebanon (LB)', value: 'LB' },
  { label: 'Lesotho (LS)', value: 'LS' },
  { label: 'Liberia (LR)', value: 'LR' },
  { label: 'Libya (LY)', value: 'LY' },
  { label: 'Liechtenstein (LI)', value: 'LI' },
  { label: 'Lithuania (LT)', value: 'LT' },
  { label: 'Luxembourg (LU)', value: 'LU' },
  { label: 'Macao (MO)', value: 'MO' },
  { label: 'Madagascar (MG)', value: 'MG' },
  { label: 'Malawi (MW)', value: 'MW' },
  { label: 'Malaysia (MY)', value: 'MY' },
  { label: 'Maldives (MV)', value: 'MV' },
  { label: 'Mali (ML)', value: 'ML' },
  { label: 'Malta (MT)', value: 'MT' },
  { label: 'Marshall Islands (MH)', value: 'MH' },
  { label: 'Martinique (MQ)', value: 'MQ' },
  { label: 'Mauritania (MR)', value: 'MR' },
  { label: 'Mauritius (MU)', value: 'MU' },
  { label: 'Mayotte (YT)', value: 'YT' },
  { label: 'Mexico (MX)', value: 'MX' },
  { label: 'Micronesia (Federated States of) (FM)', value: 'FM' },
  { label: 'Moldova (Republic of) (MD)', value: 'MD' },
  { label: 'Monaco (MC)', value: 'MC' },
  { label: 'Mongolia (MN)', value: 'MN' },
  { label: 'Montenegro (ME)', value: 'ME' },
  { label: 'Montserrat (MS)', value: 'MS' },
  { label: 'Morocco (MA)', value: 'MA' },
  { label: 'Mozambique (MZ)', value: 'MZ' },
  { label: 'Myanmar (MM)', value: 'MM' },
  { label: 'Namibia (NA)', value: 'NA' },
  { label: 'Nauru (NR)', value: 'NR' },
  { label: 'Nepal (NP)', value: 'NP' },
  { label: 'Netherlands (NL)', value: 'NL' },
  { label: 'New Caledonia (NC)', value: 'NC' },
  { label: 'New Zealand (NZ)', value: 'NZ' },
  { label: 'Nicaragua (NI)', value: 'NI' },
  { label: 'Niger (NE)', value: 'NE' },
  { label: 'Nigeria (NG)', value: 'NG' },
  { label: 'Niue (NU)', value: 'NU' },
  { label: 'Norfolk Island (NF)', value: 'NF' },
  { label: 'North Macedonia (MK)', value: 'MK' },
  { label: 'Northern Mariana Islands (MP)', value: 'MP' },
  { label: 'Norway (NO)', value: 'NO' },
  { label: 'Oman (OM)', value: 'OM' },
  { label: 'Pakistan (PK)', value: 'PK' },
  { label: 'Palau (PW)', value: 'PW' },
  { label: 'Palestine, State of (PS)', value: 'PS' },
  { label: 'Panama (PA)', value: 'PA' },
  { label: 'Papua New Guinea (PG)', value: 'PG' },
  { label: 'Paraguay (PY)', value: 'PY' },
  { label: 'Peru (PE)', value: 'PE' },
  { label: 'Philippines (PH)', value: 'PH' },
  { label: 'Pitcairn (PN)', value: 'PN' },
  { label: 'Poland (PL)', value: 'PL' },
  { label: 'Portugal (PT)', value: 'PT' },
  { label: 'Puerto Rico (PR)', value: 'PR' },
  { label: 'Qatar (QA)', value: 'QA' },
  { label: 'Réunion (RE)', value: 'RE' },
  { label: 'Romania (RO)', value: 'RO' },
  { label: 'Russian Federation (RU)', value: 'RU' },
  { label: 'Rwanda (RW)', value: 'RW' },
  { label: 'Saint Barthélemy (BL)', value: 'BL' },
  { label: 'Saint Helena (SH)', value: 'SH' },
  { label: 'Saint Kitts and Nevis (KN)', value: 'KN' },
  { label: 'Saint Lucia (LC)', value: 'LC' },
  { label: 'Saint Martin (French part) (MF)', value: 'MF' },
  { label: 'Saint Pierre and Miquelon (PM)', value: 'PM' },
  { label: 'Saint Vincent and the Grenadines (VC)', value: 'VC' },
  { label: 'Samoa (WS)', value: 'WS' },
  { label: 'San Marino (SM)', value: 'SM' },
  { label: 'São Tomé and Príncipe (ST)', value: 'ST' },
  { label: 'Saudi Arabia (SA)', value: 'SA' },
  { label: 'Senegal (SN)', value: 'SN' },
  { label: 'Serbia (RS)', value: 'RS' },
  { label: 'Seychelles (SC)', value: 'SC' },
  { label: 'Sierra Leone (SL)', value: 'SL' },
  { label: 'Singapore (SG)', value: 'SG' },
  { label: 'Sint Maarten (Dutch part) (SX)', value: 'SX' },
  { label: 'Slovakia (SK)', value: 'SK' },
  { label: 'Slovenia (SI)', value: 'SI' },
  { label: 'Solomon Islands (SB)', value: 'SB' },
  { label: 'Somalia (SO)', value: 'SO' },
  { label: 'South Africa (ZA)', value: 'ZA' },
  { label: 'South Georgia and the South Sandwich Islands (GS)', value: 'GS' },
  { label: 'South Sudan (SS)', value: 'SS' },
  { label: 'Spain (ES)', value: 'ES' },
  { label: 'Sri Lanka (LK)', value: 'LK' },
  { label: 'Sudan (SD)', value: 'SD' },
  { label: 'Suriname (SR)', value: 'SR' },
  { label: 'Svalbard and Jan Mayen (SJ)', value: 'SJ' },
  { label: 'Sweden (SE)', value: 'SE' },
  { label: 'Switzerland (CH)', value: 'CH' },
  { label: 'Syrian Arab Republic (SY)', value: 'SY' },
  { label: 'Taiwan, Province of China (TW)', value: 'TW' },
  { label: 'Tajikistan (TJ)', value: 'TJ' },
  { label: 'Tanzania, United Republic of (TZ)', value: 'TZ' },
  { label: 'Thailand (TH)', value: 'TH' },
  { label: 'Timor-Leste (TL)', value: 'TL' },
  { label: 'Togo (TG)', value: 'TG' },
  { label: 'Tokelau (TK)', value: 'TK' },
  { label: 'Tonga (TO)', value: 'TO' },
  { label: 'Trinidad and Tobago (TT)', value: 'TT' },
  { label: 'Tunisia (TN)', value: 'TN' },
  { label: 'Turkey (TR)', value: 'TR' },
  { label: 'Turkmenistan (TM)', value: 'TM' },
  { label: 'Turks and Caicos Islands (TC)', value: 'TC' },
  { label: 'Tuvalu (TV)', value: 'TV' },
  { label: 'Uganda (UG)', value: 'UG' },
  { label: 'Ukraine (UA)', value: 'UA' },
  { label: 'United Arab Emirates (AE)', value: 'AE' },
  { label: 'United Kingdom of Great Britain and Northern Ireland (GB)', value: 'GB' },
  { label: 'United States Minor Outlying Islands (UM)', value: 'UM' },
  { label: 'United States of America (US)', value: 'US' },
  { label: 'Uruguay (UY)', value: 'UY' },
  { label: 'Uzbekistan (UZ)', value: 'UZ' },
  { label: 'Vanuatu (VU)', value: 'VU' },
  { label: 'Venezuela (Bolivarian Republic of) (VE)', value: 'VE' },
  { label: 'Viet Nam (VN)', value: 'VN' },
  { label: 'Virgin Islands (British) (VG)', value: 'VG' },
  { label: 'Virgin Islands (U.S.) (VI)', value: 'VI' },
  { label: 'Wallis and Futuna (WF)', value: 'WF' },
  { label: 'Western Sahara (EH)', value: 'EH' },
  { label: 'Yemen (YE)', value: 'YE' },
  { label: 'Zambia (ZM)', value: 'ZM' },
  { label: 'Zimbabwe (ZW)', value: 'ZW' }
]

export const COUNTRY_CODES: ReadonlySet<string> = new Set(COUNTRY_CHOICES.map((choice) => choice.value))
