export const MAX_INIT_COUNT = 2

export const INIT_COUNT_KEY = 'fb_pixel_init_count'

export const USER_DATA_KEY = 'fb_user_data'

export const CURRENCY_ISO_CODES = new Set([
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BOV',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHE',
  'CHF',
  'CHW',
  'CLF',
  'CLP',
  'CNY',
  'COP',
  'COU',
  'CRC',
  'CUC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MXV',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLL',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'USN',
  'UYI',
  'UYU',
  'UYW',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XAG',
  'XAU',
  'XBA',
  'XBB',
  'XBC',
  'XBD',
  'XCD',
  'XDR',
  'XOF',
  'XPD',
  'XPF',
  'XPT',
  'XSU',
  'XTS',
  'XUA',
  'XXX',
  'YER',
  'ZAR',
  'ZMW',
  'ZWC'
])

export const US_STATE_CODES = new Map<string, string>([
  ['Arizona', 'az'],
  ['Alabama', 'al'],
  ['Alaska', 'ak'],
  ['Arkansas', 'ar'],
  ['California', 'ca'],
  ['Colorado', 'co'],
  ['Connecticut', 'ct'],
  ['Delaware', 'de'],
  ['Florida', 'fl'],
  ['Georgia', 'ga'],
  ['Hawaii', 'hi'],
  ['Idaho', 'id'],
  ['Illinois', 'il'],
  ['Indiana', 'in'],
  ['Iowa', 'ia'],
  ['Kansas', 'ks'],
  ['Kentucky', 'ky'],
  ['Louisiana', 'la'],
  ['Maine', 'me'],
  ['Maryland', 'md'],
  ['Massachusetts', 'ma'],
  ['Michigan', 'mi'],
  ['Minnesota', 'mn'],
  ['Mississippi', 'ms'],
  ['Missouri', 'mo'],
  ['Montana', 'mt'],
  ['Nebraska', 'ne'],
  ['Nevada', 'nv'],
  ['New Hampshire', 'nh'],
  ['New Jersey', 'nj'],
  ['New Mexico', 'nm'],
  ['New York', 'ny'],
  ['North Carolina', 'nc'],
  ['North Dakota', 'nd'],
  ['Ohio', 'oh'],
  ['Oklahoma', 'ok'],
  ['Oregon', 'or'],
  ['Pennsylvania', 'pa'],
  ['Rhode Island', 'ri'],
  ['South Carolina', 'sc'],
  ['South Dakota', 'sd'],
  ['Tennessee', 'tn'],
  ['Texas', 'tx'],
  ['Utah', 'ut'],
  ['Vermont', 'vt'],
  ['Virginia', 'va'],
  ['Washington', 'wa'],
  ['West Virginia', 'wv'],
  ['Wisconsin', 'wi'],
  ['Wyoming', 'wy']
])

export const COUNTRY_CODES = new Map<string, string>([
  ['Afghanistan', 'af'],
  ['Aland Islands', 'ax'],
  ['Albania', 'al'],
  ['Algeria', 'dz'],
  ['American Samoa', 'as'],
  ['Andorra', 'ad'],
  ['Angola', 'ao'],
  ['Anguilla', 'ai'],
  ['Antarctica', 'aq'],
  ['Antigua and Barbuda', 'ag'],
  ['Argentina', 'ar'],
  ['Armenia', 'am'],
  ['Aruba', 'aw'],
  ['Australia', 'au'],
  ['Austria', 'at'],
  ['Azerbaijan', 'az'],
  ['Bahamas', 'bs'],
  ['Bahrain', 'bh'],
  ['Bangladesh', 'bd'],
  ['Barbados', 'bb'],
  ['Belarus', 'by'],
  ['Belgium', 'be'],
  ['Belize', 'bz'],
  ['Benin', 'bj'],
  ['Bermuda', 'bm'],
  ['Bhutan', 'bt'],
  ['Bolivia', 'bo'],
  ['Bosnia and Herzegovina', 'ba'],
  ['Botswana', 'bw'],
  ['Bouvet Island', 'bv'],
  ['Brazil', 'br'],
  ['British Indian Ocean Territory', 'io'],
  ['Brunei Darussalam', 'bn'],
  ['Bulgaria', 'bg'],
  ['Burkina Faso', 'bf'],
  ['Burundi', 'bi'],
  ['Cambodia', 'kh'],
  ['Cameroon', 'cm'],
  ['Canada', 'ca'],
  ['Cape Verde', 'cv'],
  ['Cayman Islands', 'ky'],
  ['Central African Republic', 'cf'],
  ['Chad', 'td'],
  ['Chile', 'cl'],
  ['China', 'cn'],
  ['Christmas Island', 'cx'],
  ['Cocos (Keeling) Islands', 'cc'],
  ['Colombia', 'co'],
  ['Comoros', 'km'],
  ['Congo', 'cg'],
  ['Congo, Democratic Republic', 'cd'],
  ['Cook Islands', 'ck'],
  ['Costa Rica', 'cr'],
  ["Cote d'Ivoire", 'ci'],
  ['Croatia', 'hr'],
  ['Cuba', 'cu'],
  ['Cyprus', 'cy'],
  ['Czech Republic', 'cz'],
  ['Denmark', 'dk'],
  ['Djibouti', 'dj'],
  ['Dominica', 'dm'],
  ['Dominican Republic', 'do'],
  ['Ecuador', 'ec'],
  ['Egypt', 'eg'],
  ['El Salvador', 'sv'],
  ['Equatorial Guinea', 'gq'],
  ['Eritrea', 'er'],
  ['Estonia', 'ee'],
  ['Ethiopia', 'et'],
  ['Falkland Islands (Malvinas)', 'fk'],
  ['Faroe Islands', 'fo'],
  ['Fiji', 'fj'],
  ['Finland', 'fi'],
  ['France', 'fr'],
  ['French Guiana', 'gf'],
  ['French Polynesia', 'pf'],
  ['French Southern Territories', 'tf'],
  ['Gabon', 'ga'],
  ['Gambia', 'gm'],
  ['Georgia', 'ge'],
  ['Germany', 'de'],
  ['Ghana', 'gh'],
  ['Gibraltar', 'gi'],
  ['Greece', 'gr'],
  ['Greenland', 'gl'],
  ['Grenada', 'gd'],
  ['Guadeloupe', 'gp'],
  ['Guam', 'gu'],
  ['Guatemala', 'gt'],
  ['Guernsey', 'gg'],
  ['Guinea', 'gn'],
  ['Guinea-Bissau', 'gw'],
  ['Guyana', 'gy'],
  ['Haiti', 'ht'],
  ['Heard Island & McDonald Islands', 'hm'],
  ['Holy See (Vatican City State)', 'va'],
  ['Honduras', 'hn'],
  ['Hong Kong', 'hk'],
  ['Hungary', 'hu'],
  ['Iceland', 'is'],
  ['India', 'in'],
  ['Indonesia', 'id'],
  ['Iran, Islamic Republic of', 'ir'],
  ['Iraq', 'iq'],
  ['Ireland', 'ie'],
  ['Isle of Man', 'im'],
  ['Israel', 'il'],
  ['Italy', 'it'],
  ['Jamaica', 'jm'],
  ['Japan', 'jp'],
  ['Jersey', 'je'],
  ['Jordan', 'jo'],
  ['Kazakhstan', 'kz'],
  ['Kenya', 'ke'],
  ['Kiribati', 'ki'],
  ['Korea', 'kr'],
  ['Kuwait', 'kw'],
  ['Kyrgyzstan', 'kg'],
  ["Lao People's Democratic Republic", 'la'],
  ['Latvia', 'lv'],
  ['Lebanon', 'lb'],
  ['Lesotho', 'ls'],
  ['Liberia', 'lr'],
  ['Libyan Arab Jamahiriya', 'ly'],
  ['Liechtenstein', 'li'],
  ['Lithuania', 'lt'],
  ['Luxembourg', 'lu'],
  ['Macao', 'mo'],
  ['Macedonia', 'mk'],
  ['Madagascar', 'mg'],
  ['Malawi', 'mw'],
  ['Malaysia', 'my'],
  ['Maldives', 'mv'],
  ['Mali', 'ml'],
  ['Malta', 'mt'],
  ['Marshall Islands', 'mh'],
  ['Martinique', 'mq'],
  ['Mauritania', 'mr'],
  ['Mauritius', 'mu'],
  ['Mayotte', 'yt'],
  ['Mexico', 'mx'],
  ['Micronesia, Federated States of', 'fm'],
  ['Moldova', 'md'],
  ['Monaco', 'mc'],
  ['Mongolia', 'mn'],
  ['Montenegro', 'me'],
  ['Montserrat', 'ms'],
  ['Morocco', 'ma'],
  ['Mozambique', 'mz'],
  ['Myanmar', 'mm'],
  ['Namibia', 'na'],
  ['Nauru', 'nr'],
  ['Nepal', 'np'],
  ['Netherlands', 'nl'],
  ['Netherlands Antilles', 'an'],
  ['New Caledonia', 'nc'],
  ['New Zealand', 'nz'],
  ['Nicaragua', 'ni'],
  ['Niger', 'ne'],
  ['Nigeria', 'ng'],
  ['Niue', 'nu'],
  ['Norfolk Island', 'nf'],
  ['Northern Mariana Islands', 'mp'],
  ['Norway', 'no'],
  ['Oman', 'om'],
  ['Pakistan', 'pk'],
  ['Palau', 'pw'],
  ['Palestine', 'ps'],
  ['Panama', 'pa'],
  ['Papua New Guinea', 'pg'],
  ['Paraguay', 'py'],
  ['Peru', 'pe'],
  ['Philippines', 'ph'],
  ['Pitcairn', 'pn'],
  ['Poland', 'pl'],
  ['Portugal', 'pt'],
  ['Puerto Rico', 'pr'],
  ['Qatar', 'qa'],
  ['Reunion', 're'],
  ['Romania', 'ro'],
  ['Russian Federation', 'ru'],
  ['Rwanda', 'rw'],
  ['Saint Barthelemy', 'bl'],
  ['Saint Helena', 'sh'],
  ['Saint Kitts and Nevis', 'kn'],
  ['Saint Lucia', 'lc'],
  ['Saint Martin', 'mf'],
  ['Saint Pierre and Miquelon', 'pm'],
  ['Saint Vincent and the Grenadines', 'vc'],
  ['Samoa', 'ws'],
  ['San Marino', 'sm'],
  ['Sao Tome and Principe', 'st'],
  ['Saudi Arabia', 'sa'],
  ['Senegal', 'sn'],
  ['Serbia', 'rs'],
  ['Seychelles', 'sc'],
  ['Sierra Leone', 'sl'],
  ['Singapore', 'sg'],
  ['Slovakia', 'sk'],
  ['Slovenia', 'si'],
  ['Solomon Islands', 'sb'],
  ['Somalia', 'so'],
  ['South Africa', 'za'],
  ['South Georgia and the South Sandwich Islands', 'gs'],
  ['Spain', 'es'],
  ['Sri Lanka', 'lk'],
  ['Sudan', 'sd'],
  ['Suriname', 'sr'],
  ['Svalbard and Jan Mayen', 'sj'],
  ['Swaziland', 'sz'],
  ['Sweden', 'se'],
  ['Switzerland', 'ch'],
  ['Syrian Arab Republic', 'sy'],
  ['Taiwan', 'tw'],
  ['Tajikistan', 'tj'],
  ['Tanzania', 'tz'],
  ['Thailand', 'th'],
  ['Timor-Leste', 'tl'],
  ['Togo', 'tg'],
  ['Tokelau', 'tk'],
  ['Tonga', 'to'],
  ['Trinidad and Tobago', 'tt'],
  ['Tunisia', 'tn'],
  ['Turkey', 'tr'],
  ['Turkmenistan', 'tm'],
  ['Turks and Caicos Islands', 'tc'],
  ['Tuvalu', 'tv'],
  ['Uganda', 'ug'],
  ['Ukraine', 'ua'],
  ['United Arab Emirates', 'ae'],
  ['United Kingdom', 'gb'],
  ['United States', 'us'],
  ['United States Outlying Islands', 'um'],
  ['Uruguay', 'uy'],
  ['Uzbekistan', 'uz'],
  ['Vanuatu', 'vu'],
  ['Venezuela', 've'],
  ['Vietnam', 'vn'],
  ['Virgin Islands, British', 'vg'],
  ['Virgin Islands, U.S.', 'vi'],
  ['Wallis and Futuna', 'wf'],
  ['Western Sahara', 'eh'],
  ['Yemen', 'ye'],
  ['Zambia', 'zm'],
  ['Zimbabwe', 'zw']
])