// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Unique ID generated by the client to suppress duplicate events. The length should not exceed 128 characters.
   */
  id: string
  /**
   * Timestamp that the event happened at.
   */
  occurredAt: string | number
  /**
   * Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.
   */
  opaqueUserId: string
  /**
   * Identifier of an instance of a resolved auction for a determined banner. The length should not exceed 128 characters.
   */
  resolvedBidId: string
}
