// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' will be dropped before the perform() function call.
   */
  segment_computation_action: string
  /**
   * Unique Audience Identifier returned by the createAudience() function call.
   */
  external_audience_id: string
  /**
   * Segment Audience key.
   */
  segment_audience_key: string
  /**
   * The contact's email address.
   */
  email?: string
  /**
   * A computed object for track and identify events. This field should not need to be edited.
   */
  traits_or_props: {
    [k: string]: unknown
  }
  /**
   * When enabled, the action will batch events before sending them.
   */
  enable_batching: boolean
}
