import { ActionDefinition, PayloadValidationError } from '@segment/actions-core'
import type { Settings } from '../generated-types'
import type { Payload } from './generated-types'

const BASE_URL = 'https://api.throwaway.example.com/v1'

const action: ActionDefinition<Settings, Payload> = {
  title: 'Sync Audience',
  description: 'Sync users to a Throwaway List.',
  defaultSubscription: 'type = "identify" or type = "track"',
  fields: {
    segment_computation_action: {
      label: 'Segment Computation Action',
      description:
        "Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' will be dropped before the perform() function call.",
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_class'
      },
      choices: [{ label: 'Audience', value: 'audience' }]
    },
    external_audience_id: {
      label: 'External Audience ID',
      description: 'Unique Audience Identifier returned by the createAudience() function call.',
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.external_audience_id'
      }
    },
    segment_audience_key: {
      label: 'Audience Key',
      description: 'Segment Audience key.',
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_key'
      }
    },
    email: {
      label: 'Email',
      description: "The contact's email address.",
      type: 'string',
      format: 'email',
      default: {
        '@if': {
          exists: { '@path': '$.traits.email' },
          then: { '@path': '$.traits.email' },
          else: { '@path': '$.context.traits.email' }
        }
      }
    },
    traits_or_props: {
      label: 'Traits or Properties',
      description: 'A computed object for track and identify events. This field should not need to be edited.',
      type: 'object',
      required: true,
      unsafe_hidden: true,
      default: {
        '@if': {
          exists: { '@path': '$.properties' },
          then: { '@path': '$.properties' },
          else: { '@path': '$.traits' }
        }
      }
    },
    enable_batching: {
      label: 'Enable Batching',
      description: 'When enabled, the action will batch events before sending them.',
      type: 'boolean',
      required: true,
      default: true
    }
  },
  perform: async (request, { payload }) => {
    return await send(request, [payload])
  },
  performBatch: async (request, { payload }) => {
    return await send(request, payload)
  }
}

async function send(
  request: Parameters<NonNullable<ActionDefinition<Settings, Payload>['perform']>>[0],
  payloads: Payload[]
) {
  const externalAudienceId = payloads[0]?.external_audience_id
  if (!externalAudienceId) {
    throw new PayloadValidationError('external_audience_id is required')
  }

  const contacts = payloads.map((payload) => {
    const audienceKey = payload.segment_audience_key
    const isMember = Boolean((payload.traits_or_props ?? {})[audienceKey])
    return {
      email: payload.email,
      action: isMember ? 'add' : 'remove'
    }
  })

  return request(`${BASE_URL}/lists/${externalAudienceId}/contacts`, {
    method: 'POST',
    json: { contacts }
  })
}

export default action
