// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Details about the event to be sent to Rokt CAPI.
   */
  eventDetails: {
    /**
     * Type of conversion, This should usually be mapped to the Segment track() event name. e.g., "Order Completed".
     */
    conversiontype?: string
    /**
     * Unique ID for the conversion, ideally an order ID.
     */
    confirmationref?: string
    /**
     * Monetary amount associated with the conversion.
     */
    amount?: number
    /**
     * 3-letter ISO currency code (e.g. USD, EUR).
     */
    currency?: string
    /**
     * Unique identifier for the source message.
     */
    source_message_id: string
    /**
     * Event timestamp in Unix time milliseconds.
     */
    timestamp_unixtime_ms: string
  }
  /**
   * Additional custom attributes for the event.
   */
  eventProperties?: {
    [k: string]: unknown
  }
  /**
   * Specify if email and certain user attributes should be hashed before sending.
   */
  hashingConfiguration?: {
    /**
     * If enabled, Segment will ensure that the email address is hashed using SHA256 before sending.
     */
    hashEmail?: boolean
    /**
     * If enabled, Segment will ensure that the first name is hashed using SHA256 before sending.
     */
    hashFirstName?: boolean
    /**
     * If enabled, Segment will ensure that the last name is hashed using SHA256 before sending.
     */
    hashLastName?: boolean
    /**
     * If enabled, Segment will ensure that the mobile number is hashed using SHA256 before sending.
     */
    hashMobile?: boolean
    /**
     * If enabled, Segment will ensure that the billing zip code is hashed using SHA256 before sending.
     */
    hashBillingZipcode?: boolean
  }
  /**
   * Information about the user device.
   */
  device_info?: {
    /**
     * Device user agent.
     */
    http_header_user_agent?: string
    /**
     * Advertising ID from an iOS mobile device.
     */
    ios_advertising_id?: string
    /**
     * Advertising ID from an Android mobile device.
     */
    android_advertising_id?: string
    /**
     * ID for Vendor from an iOS mobile device.
     */
    ios_idfv?: string
    /**
     * UUID from an Android mobile device.
     */
    android_uuid?: string
  }
  /**
   * Unique user identifiers used to identify the user. At least one identifier is required, or the advertising ID in device info.
   */
  user_identities?: {
    /**
     * User email address. This can be in plain text or hashed using SHA256. If you send plain text and would like Segment to hash the email address for you, enable the "Hash Email" field.
     */
    email?: string
    /**
     * Unique customer identifier.
     */
    customerid?: string
    /**
     * ROKT Click ID.
     */
    other2?: string
  }
  /**
   * Attributes related to the user.
   */
  user_attributes?: {
    /**
     * User first name.
     */
    firstname?: string
    /**
     * User last name.
     */
    lastname?: string
    /**
     * User mobile number.
     */
    mobile?: string
    /**
     * User billing zip code.
     */
    billingzipcode?: string
    /**
     * User date of birth in ISO8601 format (YYYY-MM-DD).
     */
    dob?: string
    /**
     * User gender
     */
    gender?: string
    [k: string]: unknown
  }
  /**
   * IP address of the user.
   */
  ip?: string
  /**
   * Details of the audience to add the user to or remove the user from. If connecting to a Segment Engage Audience, leave this field empty.
   */
  audienceDetails?: {
    /**
     * Name of the audience for audience membership updates. If connecting to a Segment Engage Audience leave the field empty.
     */
    customAudienceName?: string
    /**
     * Boolean indicating whether the user is a member of the audience. If connecting to a Segment Engage Audience leave this field empty.
     */
    customAudienceMembership?: boolean
  }
  /**
   * Hidden field used figure out audience membership when syncing an Engage Audience.
   */
  engageFields?: {
    /**
     * Name of the audience for audience membership updates. If connecting to a Segment Engage Audience, leave the detault mapping as is.
     */
    engageAudienceName?: string
    /**
     * Object that contains audience name and value.
     */
    traitsOrProps?: {
      [k: string]: unknown
    }
    /**
     * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
     */
    computationAction?: string
  }
  /**
   * Maximum number of events to include in each batch. Actual batch sizes may be lower.
   */
  batch_size?: number
  /**
   * Enable sending events in batches.
   */
  enable_batching?: boolean
}
