import type { ActionDefinition } from '@segment/actions-core'
import type { Settings } from '../generated-types'
import type { Payload } from './generated-types'

const action: ActionDefinition<Settings, Payload> = {
  title: 'Sync Audience',
  description: 'Sync Engage Audiences to MediaMath',
  defaultSubscription: 'type = "identify" or type = "track"',
  fields: {
    segment_computation_id: {
      label: 'Computation ID',
      description: 'Segment Computation ID',
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_id'
      }
    },
    segment_computation_key: {
      label: 'Computation Key',
      description: 'Segment Audience key',
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_key'
      }
    },
    segment_computation_action: {
      label: 'Segment Computation Action',
      description:
        "Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.",
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_class'
      },
      choices: [{ label: 'audience', value: 'audience' },{ label: 'journey_step', value: 'journey_step' }]
    },
    traits_or_props: {
      label: 'Traits or properties object',
      description: 'Traits or properties object.',
      type: 'object',
      required: true,
      unsafe_hidden: true,
      default: {
        '@if': {
          exists: { '@path': '$.properties' },
          then: { '@path': '$.properties' },
          else: { '@path': '$.traits' }
        }
      }
    },
    enable_batching: {
      type: 'boolean',
      label: 'Batch events',
      description:
        'When enabled, the action will batch events before sending them to LaunchDarkly. In most cases, batching should be enabled.',
      required: false,
      unsafe_hidden: true,
      default: true
    },

    // user identifier details below

    segment_user_id: {
      label: 'Segment User ID',
      description: 'The Segment userId value.',
      type: 'string',
      unsafe_hidden: true,
      required: false,
      default: { '@path': '$.userId' }
    },
    segment_anonymous_id: {
      label: 'Segment Anonymous ID',
      description: 'The Segment anonymousId value.',
      type: 'string',
      unsafe_hidden: true,
      required: false,
      default: { '@path': '$.anonymousId' }
    },
    user_email: {
      label: 'Email address',
      description: "The user's email address",
      type: 'string',
      unsafe_hidden: true,
      required: false,
      default: {
        '@if': {
          exists: { '@path': '$.traits.email' },
          then: { '@path': '$.traits.email' },
          else: { '@path': '$.context.traits.email' }
        }
      }
    },
  },
  perform: async (request, { settings, payload }) => {
    return send(request, settings, [payload])
  },
  performBatch: async (request, { settings, payload }) => {
    return send(request, settings, payload)
  }
}

export default action
