import type { DestinationDefinition } from '@segment/actions-core'
import type { Settings } from './generated-types'

import trackEvent from './trackEvent'

import identify from './identify'

import group from './group'

import page from './page'

import screen from './screen'
import { getAuthUrl } from './api'

const destination: DestinationDefinition<Settings> = {
  name: 'Canvas',
  slug: 'actions-canvas',
  mode: 'cloud',

  authentication: {
    scheme: 'custom',
    fields: {
      apiToken: {
        label: 'API Token',
        description: 'API token generated by Canvas',
        type: 'password'
      }
    },
    testAuthentication: (request) => {
      return request(getAuthUrl())
    }
  },
  extendRequest({ settings: { apiToken } }) {
    return {
      headers: {
        Authorization: `Bearer ${apiToken}`
      }
    }
  },

  actions: {
    trackEvent,
    identify,
    group,
    page,
    screen
  }
}

export default destination
