import { InputField } from '@segment/actions-core'
import {
  is_append_event,
  append_event_details,
  currency,
  value,
  net_revenue,
  predicted_ltv,
  content_name,
  content_type,
  contents,
  custom_data,
  num_items,
  content_ids,
  event_time,
  action_source,
  event_source_url,
  event_id,
  order_id,
  data_processing_options,
  data_processing_options_country,
  data_processing_options_state,
  test_event_code
} from '../fb-capi-properties'
import { app_data_field } from '../fb-capi-app-data'

// Implementation of Facebook user data object
// https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters
const user_data_field: InputField = {
  label: 'User Data',
  description:
    'These parameters are a set of identifiers Facebook can use for targeted attribution. You must provide at least one of the following parameters in your request. More information on recommended User Data parameters in Facebook’s [Best Practices for Conversions API](https://www.facebook.com/business/help/308855623839366).',
  type: 'object',
  required: true,
  properties: {
    externalId: {
      label: 'External ID',
      description:
        'Any unique ID from the advertiser, such as loyalty membership IDs, user IDs, and external cookie IDs. You can send one or more external IDs for a given event.',
      type: 'string',
      multiple: true, // changed the type from string to array of strings.
      category: 'hashedPII'
    },
    email: {
      label: 'Email',
      description: 'An email address in lowercase.',
      type: 'string',
      category: 'hashedPII'
    },
    phone: {
      label: 'Phone',
      description:
        'A phone number. Include only digits with country code, area code, and number. Remove symbols, letters, and any leading zeros. In addition, always include the country code, even if all of the data is from the same country, as the country code is used for matching.',
      type: 'string',
      category: 'hashedPII'
    },
    gender: {
      label: 'Gender',
      description: 'Gender in lowercase. Either f or m.',
      type: 'string',
      category: 'hashedPII'
    },
    dateOfBirth: {
      label: 'Date of Birth',
      description: 'A date of birth given as year, month, and day. Example: 19971226 for December 26, 1997.',
      type: 'string',
      category: 'hashedPII'
    },
    lastName: {
      label: 'Last Name',
      description: 'A last name in lowercase.',
      type: 'string',
      category: 'hashedPII'
    },
    firstName: {
      label: 'First Name',
      description: 'A first name in lowercase.',
      type: 'string',
      category: 'hashedPII'
    },
    city: {
      label: 'City',
      description: 'A city in lowercase without spaces or punctuation. Example: menlopark.',
      type: 'string',
      category: 'hashedPII'
    },
    state: {
      label: 'State',
      description: 'A two-letter state code in lowercase. Example: ca.',
      type: 'string',
      category: 'hashedPII'
    },
    zip: {
      label: 'Zip Code',
      description: 'A five-digit zip code for United States. For other locations, follow each country`s standards.',
      type: 'string',
      category: 'hashedPII'
    },
    country: {
      label: 'Country',
      description: 'A two-letter country code in lowercase.',
      type: 'string',
      category: 'hashedPII'
    },
    client_ip_address: {
      label: 'Client IP Address',
      description: 'The IP address of the browser corresponding to the event.',
      type: 'string'
    },
    client_user_agent: {
      label: 'Client User Agent',
      description:
        'The user agent for the browser corresponding to the event. This is required if action source is “website”.',
      type: 'string'
    },
    fbc: {
      label: 'Click ID',
      description: 'The Facebook click ID value stored in the _fbc browser cookie under your domain.',
      type: 'string'
    },
    fbp: {
      label: 'Browser ID',
      description: 'The Facebook browser ID value stored in the _fbp browser cookie under your domain.',
      type: 'string'
    },
    subscriptionID: {
      label: 'Subscription ID',
      description: 'The subscription ID for the user in this transaction.',
      type: 'string'
    },
    leadID: {
      label: 'Lead ID',
      description: 'The ID associated with a lead generated by Facebook`s Lead Ads.',
      type: 'integer'
    },
    fbLoginID: {
      label: 'Facebook Login ID',
      description: 'The ID issued by Facebook when a person first logs into an instance of an app.',
      type: 'integer'
    },
    anonId: {
      label: 'Install ID (anon_id)',
      description:
        'This field represents unique application installation instances. Note: This parameter is for app events only.',
      type: 'string'
    },
    madId: {
      label: 'Advertiser ID (madid)',
      description:
        'Your mobile advertiser ID, the advertising ID from an Android device or the Advertising Identifier (IDFA) from an Apple device.',
      type: 'string'
    },
    partner_id: {
      label: 'Partner ID',
      description: 'The ID issued by Facebook identity partner.',
      type: 'string'
    },
    partner_name: {
      label: 'Partner Name',
      description: 'The name of the Facebook identity partner.',
      type: 'string'
    }
  },
  default: {
    externalId: {
      '@if': {
        exists: { '@path': '$.userId' },
        then: { '@path': '$.userId' },
        else: { '@path': '$.anonymousId' }
      }
    },
    email: {
      '@path': '$.context.traits.email'
    },
    phone: {
      '@path': '$.context.traits.phone'
    },
    dateOfBirth: {
      '@path': '$.context.traits.birthday'
    },
    lastName: {
      '@path': '$.context.traits.lastName'
    },
    firstName: {
      '@path': '$.context.traits.firstName'
    },
    city: {
      '@path': '$.context.traits.address.city'
    },
    state: {
      '@path': '$.context.traits.address.state'
    },
    zip: {
      '@path': '$.context.traits.address.postalCode'
    },
    client_ip_address: {
      '@path': '$.context.ip'
    },
    client_user_agent: {
      '@path': '$.context.userAgent'
    },
    fbc: {
      '@path': '$.properties.fbc'
    },
    fbp: {
      '@path': '$.properties.fbp'
    }
  }
}

export const fields: Record<string, InputField> =  {
  is_append_event,
  append_event_details,
  action_source: { ...action_source, required: true },
  currency: { ...currency, required: true },
  event_time: { ...event_time, required: true },
  user_data: user_data_field,
  app_data_field,
  value: {
    ...value,
    required: true,
    default: { '@path': '$.properties.revenue' }
  },
  net_revenue,
  predicted_ltv,
  content_ids,
  content_name,
  content_type,
  contents: {
    // Segment Checkout Started has an array of products mapping
    ...contents,
    default: {
      '@arrayPath': [
        '$.properties.products',
        {
          id: {
            '@path': '$.product_id'
          },
          quantity: {
            '@path': '$.quantity'
          },
          item_price: {
            '@path': '$.price'
          }
        }
      ]
    }
  },
  event_id,
  order_id,
  event_source_url,
  num_items,
  custom_data,
  data_processing_options,
  data_processing_options_country,
  data_processing_options_state,
  test_event_code
}

