// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
   */
  segment_computation_action: string
  /**
   * Segment's friendly name for the Audience
   */
  computation_key: string
  /**
   * Unique Audience Identifier returned by the createAudience() function call.
   */
  external_audience_id: string
  /**
   * The Contact's email address.
   */
  emailIdentifier?: string
  /**
   * The Contact's mobile number.
   */
  mobileNumberIdentifier?: string
  /**
   * A computed object for track and identify events. This field should not need to be edited.
   */
  traits_or_props: {
    [k: string]: unknown
  }
  /**
   * An object containing key/value pairs for data fields assigned to this Contact. Custom Data Fields must already be defined in Dotdigital.
   */
  dataFields?: {
    [k: string]: unknown
  }
}
