// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Name of custom audience to add or remove the user from
   */
  custom_audience_name: string
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
   */
  segment_computation_action: string
  /**
   * Segment computation ID
   */
  segment_computation_id: string
  /**
   * The user identifier to sync to the Optimizely Audience
   */
  optimizelyUserId: string
  /**
   * Timestamp indicates when the user was added or removed from the Audience
   */
  timestamp: string
  /**
   * Enable batching of event data to Optimizely.
   */
  enable_batching?: boolean
  /**
   * Number of events to batch before sending to Optimizely.
   */
  batch_size?: number
}
