// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * The payload to send to Zapier
   */
  data: {
    [k: string]: unknown
  }
  /**
   * The Zapier webhook URL Segment will send data to. This URL is generated by Zapier when you create a Zap.
   */
  zapSubscriptionUrl: string
  /**
   * The Zapier Zap identifier. This is generated by Zapier when you create a Zap.
   */
  zapIdentifier?: string
  /**
   * The initial Segment FQL query for the Action mapping. This is generated by Zapier when you create a Zap.
   */
  fql?: string
}
