import { ActionDefinition, PayloadValidationError } from '@segment/actions-core'
import type { Settings } from '../generated-types'
import type { Payload } from './generated-types'

const action: ActionDefinition<Settings, Payload> = {
  title: 'Send',
  description: 'Send any Segment event to Zapier',
  fields: {
    data: {
      label: 'Payload',
      description: 'The payload to send to Zapier',
      type: 'object',
      required: true,
      default: { '@path': '$.'}
    },
    zapSubscriptionUrl: {
      label: 'Zapier Webhook URL',
      description: 'The Zapier webhook URL Segment will send data to. This URL is generated by Zapier when you create a Zap.',
      type: 'string',
      format: 'password',
      readOnly: false,
      required: true
    },
    zapIdentifier: {
      label: 'Zapier Zap Identifier',
      description: 'The Zapier Zap identifier. This is generated by Zapier when you create a Zap.',
      type: 'string',
      readOnly: false,
      required: false
    },
    fql: {
      label: 'Segment FQL Query',
      description: 'The initial Segment FQL query for the Action mapping. This is generated by Zapier when you create a Zap.',
      type: 'string',
      readOnly: false,
      required: false
    }
  },
  perform: (request, { payload }) => {
    const { zapSubscriptionUrl, data} = payload    
    const hosts = ['zapier.com', 'zapier-staging.com']

    // check that the hostname ends with one of the hosts values 
    const url: URL = new URL(zapSubscriptionUrl)
    if (!hosts.some((host) => url.hostname.endsWith(host))) {
      throw new PayloadValidationError(`Invalid Zapier Webhook URL hostname: ${url.hostname}. Must end with one of: ${hosts.join(', ')}`)
    }

    return request(zapSubscriptionUrl, {
      method: 'post',
      json: data
    })
  }
}

export default action
