import { InputField } from '@segment/actions-core'

export const fields: Record<string, InputField> = {
    user_identifier: {
        label: 'User Identifier',
        description: 'The identifier for the user. This can be either the user_id or device_id in Amplitude. If both are present, user_id will be used.',
        type: 'string',
        required: true,
        defaultObjectUI: 'keyvalue',
        additionalProperties: false,
        properties: {
            user_id: {
                label: 'User ID',
                description: 'User ID',
                type: 'string'
            },
            amplitude_id: {
                label: 'Amplitude ID',
                description: 'Amplitude ID',
                type: 'string'
            }
        },
        default: {
            user_id: { '@path': '$.userId' }
        }
    },
    traits_or_properties: {
        label: 'Traits or Properties',
        description: 'Traits or Properties object from the identify() or track() call emitted by Engage',
        type: 'object',
        required: true,
        default: {
            '@if': {
                exists: { '@path': '$.traits' },
                then: { '@path': '$.traits' },
                else: { '@path': '$.properties' }
            }
        }     
    },
    segment_computation_class: {
      label: 'Segment Computation Class',
      description:
        "Hidden field used to verify that the payload is generated by an Engage Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.",
      type: 'string',
      unsafe_hidden: true,
      required: true,
      default: {
        '@path': '$.context.personas.computation_class'
      },
      choices: [
        { label: 'audience', value: 'audience' },
        { label: 'journey_step', value: 'journey_step' }
      ]
    },
    segment_audience_key: {
        label: 'Segment Audience Key',
        description: 'Hidden field used to determine whether to add or remove the user from the Amplitude Cohort.',
        type: 'string',
        unsafe_hidden: true,
        required: true,
        default: {
            '@path': '$.context.personas.computation_key'
        }
    },
    cohort_id: {
        label: 'Cohort ID',
        description: 'Hidden field containing the Cohort ID which was returned when the Amplitude Cohort was created in the Audience Settings.',
        type: 'string',
        unsafe_hidden: true,
        required: true,
        default: {
            '@path': '$.context.personas.external_audience_id'
        }
    },
    batch_size: {
        label: 'Max Batch Size',
        description: 'The maximum number of users to process in a single batch request.',
        type: 'number',
        required: true,
        default: 100,
        maximum: 500,
        minimum: 1
    }
}