import { InputField } from '@segment/actions-core'

export const fields: Record<string, InputField> = {
    user_id: {
        label: 'User ID',
        description: 'Required if "ID Type" is set to "User ID".',
        type: 'string',
        default: { '@path': '$.userId' }
    },
    amplitude_id: {
        label: 'Amplitude ID',
        description: 'Required if "ID Type" is set to "Amplitude ID".',
        type: 'string'
    },
    engage_fields: {
        label: 'Engage Fields',
        description: 'Fields from the identify() or track() call emitted by Engage. This is used to determine whether the user should be added or removed from the Amplitude Cohort.',
        type: 'object',
        required: true,
        properties: {
            segment_computation_class: {
                label: 'Segment Computation Class',
                description:
                    "Hidden field used to verify that the payload is generated by an Engage Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.",
                type: 'string',
                unsafe_hidden: true,
                required: true,
                choices: [
                    { label: 'audience', value: 'audience' },
                    { label: 'journey_step', value: 'journey_step' }
                ]
            },
            traits_or_properties: {
                label: 'Traits or Properties',
                description: 'Traits or Properties object from the identify() or track() call emitted by Engage',
                type: 'object',
                required: true    
            },
            segment_audience_key: {
                label: 'Segment Audience Key',
                description: 'Hidden field used to determine whether to add or remove the user from the Amplitude Cohort.',
                type: 'string',
                unsafe_hidden: true,
                required: true
            },
            segment_external_audience_id: {
                label: 'Segment External Audience ID',
                description: 'Hidden field containing the Cohort ID which was returned when the Amplitude Cohort was created in the Audience Settings.',
                type: 'string',
                unsafe_hidden: true,
                required: true
            }
        },
        default: {
            segment_computation_class: { '@path': '$.context.personas.computation_class'},
            traits_or_properties: {
                '@if': {
                    exists: { '@path': '$.traits' },
                    then: { '@path': '$.traits' },
                    else: { '@path': '$.properties' }
                }
            },
            segment_audience_key: { '@path': '$.context.personas.computation_key' }, 
            segment_external_audience_id: {'@path': '$.context.personas.external_audience_id' }
        }
    },
    batch_size: {
        label: 'Max Batch Size',
        description: 'The maximum number of users to process in a single batch request.',
        type: 'number',
        required: true,
        default: 100,
        maximum: 500,
        minimum: 1
    }
}