// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * The type of user identifier you want to use when syncing the Engage Audience to the Amplitude Cohort.
   */
  id_type: string
  /**
   * Required if "ID Type" is set to "User ID".
   */
  user_id?: string
  /**
   * Required if "ID Type" is set to "Amplitude ID".
   */
  amplitude_id?: string
  /**
   * Fields from the identify() or track() call emitted by Engage. This is used to determine whether the user should be added or removed from the Amplitude Cohort.
   */
  engage_fields: {
    /**
     * Hidden field used to verify that the payload is generated by an Engage Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
     */
    segment_computation_class: string
    /**
     * Traits or Properties object from the identify() or track() call emitted by Engage
     */
    traits_or_properties: {
      [k: string]: unknown
    }
    /**
     * Hidden field used to determine whether to add or remove the user from the Amplitude Cohort.
     */
    segment_audience_key: string
    /**
     * Hidden field containing the Cohort ID which was returned when the Amplitude Cohort was created in the Audience Settings.
     */
    segment_external_audience_id: string
  }
  /**
   * The maximum number of users to process in a single batch request.
   */
  batch_size: number
  /**
   * The keys to use for batching the events.
   */
  batch_keys?: string[]
}
