// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * User ID
   */
  user_id: string
  /**
   * The time the event occurred, in milliseconds since epoch.
   */
  time: string | number
  /**
   * Additional data tied to the user in Amplitude. Each distinct value will show up as a user segment on the Amplitude dashboard. Object depth may not exceed 40 layers.
   */
  user_properties?: {
    [k: string]: unknown
  }
  /**
   * Traits or Properties object from the identify() or track() call emitted by Engage
   */
  traits_or_properties: {
    [k: string]: unknown
  }
  /**
   * Hidden field used to verify that the payload is generated by an Engage Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
   */
  segment_computation_class: string
  /**
   * Hidden field used to determine whether to add or remove the user from the Amplitude Cohort.
   */
  segment_audience_key: string
  /**
   * Hidden field containing the Cohort ID which was returned when the Amplitude Cohort was created in the Audience Settings.
   */
  cohort_id: string
  /**
   * The maximum number of users to process in a single batch request.
   */
  batch_size: number
}
