// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Segment event message ID
   */
  message_id: string
  /**
   * Segment event timestamp
   */
  timestamp: string | number
  /**
   * Unique Audience Identifier returned by the createAudience() function call.
   */
  external_audience_id: string
  /**
   * Segment Audience key / name
   */
  segment_audience_key: string
  /**
   * Traits or Properties object
   */
  traits_or_props: {
    [k: string]: unknown
  }
  /**
   * Hidden field used to verify that the payload is generated by an Audience. Payloads not containing computation_class = 'audience' or 'journey_step' will be dropped before the perform() fuction call.
   */
  segment_computation_action: string
  /**
   * User's email address
   */
  email?: string
  /**
   * User's anonymousId
   */
  anonymousId?: string
  /**
   * User's unique User ID
   */
  userId?: string
}
