// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * The ID of the app that created the order.
   */
  app_id?: string
  /**
   * The mailing address associated with the payment method.
   */
  billing_address?: {
    /**
     * A unique identifier for the address.
     */
    id?: string
    /**
     * The customer's mailing address.
     */
    address1?: string
    /**
     * An additional field for the customer's mailing address.
     */
    address2?: string
    /**
     * The customer's city, town, or village.
     */
    city?: string
    /**
     * The customer's company.
     */
    company?: string
    /**
     * The customer's country.
     */
    country?: string
    /**
     * The two-letter country code corresponding to the customer's country
     */
    country_code?: string
    /**
     * The customer's normalized country name.
     */
    country_name?: string
    /**
     * A unique identifier for the customer.
     */
    customer_id?: string
    /**
     * Whether this address is the default address for the customer.
     */
    default?: boolean
    /**
     * The customer's first name.
     */
    first_name?: string
    /**
     * The customer's last name.
     */
    last_name?: string
    /**
     * The customer's first and last names.
     */
    name?: string
    /**
     * The customer's phone number at this address.
     */
    phone?: string
    /**
     * The customer's region name. Typically a province, a state, or a prefecture
     */
    province?: string
    /**
     * The code for the region of the address, such as the province, state, or district. For example QC for Quebec, Canada.
     */
    province_code?: string
    /**
     * The customer's postal code, also known as zip, postcode, Eircode, etc
     */
    zip?: string
    /**
     * Hashed value of first name in SHA256 (lower case).
     */
    hashed_first_name?: string
    /**
     * Hashed value of last name in SHA256 (lower case).
     */
    hashed_last_name?: string
    /**
     * Hashed value of phone in SHA256 (lower case).
     */
    hashed_phone?: string
    /**
     * Hashed value of address1 in SHA256 (lower case).
     */
    hashed_address1?: string
    /**
     * Hashed value of address2 in SHA256 (lower case).
     */
    hashed_address2?: string
    /**
     * Hashed value of city in SHA256 (lower case).
     */
    hashed_city?: string
    /**
     * Hashed value of zip in SHA256 (lower case).
     */
    hashed_zip?: string
    /**
     * Hashed value of country code in SHA256 (lower case).
     */
    hashed_country_code?: string
  }
  /**
   * The IP address of the browser used by the customer when they placed the order. Both IPv4 and IPv6 are supported.
   */
  browser_ip?: string
  /**
   * Whether the customer consented to receive email updates from the shop.
   */
  buyer_accepts_marketing?: boolean
  /**
   * The reason why the order was canceled.
   */
  cancel_reason?: string
  /**
   * The date and time when the order was canceled. Returns null if the order isn't canceled.
   */
  cancelled_at?: string
  /**
   * The ID of the checkout.
   */
  checkout_id?: string
  /**
   * Information about the browser that the customer used when they placed their order.
   */
  client_details?: {
    /**
     * The languages and locales that the browser understands.
     */
    accept_language?: string
    /**
     * The browser screen height in pixels, if available.
     */
    browser_height?: number
    /**
     * The browser IP address.
     */
    browser_ip?: string
    /**
     * The browser screen width in pixels, if available.
     */
    browser_width?: number
    /**
     * A hash of the session.
     */
    session_hash?: string
    /**
     * Details of the browsing client, including software and operating versions.
     */
    user_agent?: string
  }
  /**
   * The date and time (ISO 8601 format) when the order was closed.
   */
  closed_at?: string
  confirmed?: boolean
  contact_email?: string
  /**
   * The autogenerated date and time (ISO 8601 format) when the order was created.
   */
  created_at?: string
  /**
   * The three-letter code (ISO 4217 format) for the currency that the customer used when they paid for their last order.
   */
  currency?: string
  /**
   * The current subtotal price of the order in the shop currency. The value of this field reflects order edits, returns, and refunds.
   */
  current_subtotal_price?: string
  /**
   * The current total discounts on the order in the shop currency. The value of this field reflects order edits, returns, and refunds.
   */
  current_total_discounts?: string
  /**
   * The current total price of the order in the shop currency. The value of this field reflects order edits, returns, and refunds.
   */
  current_total_price?: string
  /**
   * The current total taxes charged on the order in the shop currency. The value of this field reflects order edits, returns, or refunds.
   */
  current_total_tax?: string
  /**
   * A unique identifier for the customer.
   */
  customer_id?: string
  /**
   * An ordered list of stacked discount applications. The discount_applications property includes 3 types: discount_code, manual, and script. All 3 types share a common structure and have some type specific attributes.
   */
  discount_applications?: {
    /**
     * The type of line on the order that the discount is applicable on.
     */
    target_type?: string
    /**
     * The discount application type.
     */
    type?: string
    /**
     * The value of the discount application as a decimal. This represents the intention of the discount application.
     */
    value?: string
    /**
     * The type of the value.
     */
    value_type?: string
    /**
     * The method by which the discount application value has been allocated to entitled lines.
     */
    allocation_method?: string
    /**
     * The lines on the order, of the type defined by target_type, that the discount is allocated over.
     */
    target_selection?: string
    /**
     * The discount code that was used to apply the discount. Available only for discount code applications.
     */
    code?: string
  }[]
  /**
   * A list of discounts applied to the order.
   */
  discount_codes?: {
    /**
     * When the associated discount application is of type code, this property returns the discount code that was entered at checkout. Otherwise this property returns the title of the discount that was applied.
     */
    code?: string
    /**
     * The amount that's deducted from the order total. When you create an order, this value is the percentage or monetary amount to deduct. After the order is created, this property returns the calculated amount.
     */
    amount?: string
    /**
     * The type of discount.
     */
    type?: string
  }[]
  /**
   * The customer's email address.
   */
  email?: string
  /**
   * Whether taxes on the order are estimated. Many factors can change between the time a customer places an order and the time the order is shipped, which could affect the calculation of taxes.
   */
  estimated_taxes?: boolean
  /**
   * The status of payments associated with the order.
   */
  financial_status?: string
  /**
   * The order's status in terms of fulfilled line items.
   */
  fulfillment_status?: string
  /**
   * An array of fulfillments associated with the order.
   */
  fulfillments?: {
    /**
     * The ID for the fulfillment.
     */
    id?: string
    /**
     * The date and time (ISO 8601 format) when the fulfillment was created.
     */
    created_at?: string
    /**
     * The unique numeric identifier for the order.
     */
    order_id?: string
    /**
     * The current shipment status of the fulfillment.
     */
    shipment_status?: string
    /**
     * The status of the fulfillment.
     */
    status?: string
    /**
     * The name of the tracking company.
     */
    tracking_company?: string
    /**
     * The date and time (ISO 8601 format) when the fulfillment was last modified.
     */
    updated_at?: string
  }[]
  /**
   * The payment gateway used.
   */
  gateway?: string
  /**
   * The ID of the order, used for API purposes.
   */
  id: string
  /**
   * The URL for the page where the buyer landed when they entered the shop.
   */
  landing_site?: string
  landing_site_ref?: string
  /**
   * The ID of one of the locations that was assigned to fulfill the order when the order was created.
   */
  location_id?: string
  /**
   * The order name.
   */
  name?: string
  /**
   * An optional note that a shop owner can attach to the order.
   */
  note?: string
  /**
   * Extra information that is added to the order.
   */
  note_attributes?: {
    /**
     * Extra property name.
     */
    name?: string
    /**
     * Extra property value.
     */
    value?: string
  }[]
  /**
   * The order's position in the shop's count of orders. Numbers are sequential and start at 1.
   */
  number?: number
  /**
   * The order position in the shop count of orders starting at 1001. Order numbers are sequential and start at 1001.
   */
  order_number?: number
  /**
   * An object containing information about the payment.
   */
  payment_details?: {
    /**
     * The issuer identification number (IIN), formerly known as the bank identification number (BIN), of the customer's credit card. This is made up of the first few digits of the credit card number.
     */
    credit_card_bin?: string
    /**
     * The response code from the address verification system (AVS). The code is a single letter. See this chart for the codes and their definitions.
     */
    avs_result_code?: string
    /**
     * The response code from the credit card company indicating whether the customer entered the card security code (card verification value) correctly. The code is a single letter or empty string. See this chart for the codes and their definitions.
     */
    cvv_result_code?: string
    /**
     * The customer's credit card number, with most of the leading digits redacted.
     */
    credit_card_number?: string
    /**
     * The customer's credit card name.
     */
    credit_card_name?: string
    /**
     * The customer's credit card wallet.
     */
    credit_card_wallet?: string
    /**
     * The customer's credit card expiration month.
     */
    credit_card_expiration_month?: string
    /**
     * The customer's credit card expiration year.
     */
    credit_card_expiration_year?: string
  }
  /**
   * The customer's phone number for receiving SMS notifications.
   */
  phone?: string
  /**
   * The presentment currency that was used to display prices to the customer.
   */
  presentment_currency?: string
  /**
   * The date and time (ISO 8601 format) when an order was processed.
   */
  processed_at?: string
  /**
   * How the payment was processed.
   */
  processing_method?: string
  reference?: string
  /**
   * The website where the customer clicked a link to the shop.
   */
  referring_site?: string
  /**
   * The mailing address associated with the payment method.
   */
  shipping_address?: {
    /**
     * A unique identifier for the address.
     */
    id?: string
    /**
     * The customer's mailing address.
     */
    address1?: string
    /**
     * An additional field for the customer's mailing address.
     */
    address2?: string
    /**
     * The customer's city, town, or village.
     */
    city?: string
    /**
     * The customer's company.
     */
    company?: string
    /**
     * The customer's country.
     */
    country?: string
    /**
     * The two-letter country code corresponding to the customer's country
     */
    country_code?: string
    /**
     * The customer's normalized country name.
     */
    country_name?: string
    /**
     * A unique identifier for the customer.
     */
    customer_id?: string
    /**
     * Whether this address is the default address for the customer.
     */
    default?: boolean
    /**
     * The customer's first name.
     */
    first_name?: string
    /**
     * The customer's last name.
     */
    last_name?: string
    /**
     * The customer's first and last names.
     */
    name?: string
    /**
     * The customer's phone number at this address.
     */
    phone?: string
    /**
     * The customer's region name. Typically a province, a state, or a prefecture
     */
    province?: string
    /**
     * The code for the region of the address, such as the province, state, or district. For example QC for Quebec, Canada.
     */
    province_code?: string
    /**
     * The customer's postal code, also known as zip, postcode, Eircode, etc
     */
    zip?: string
    /**
     * Hashed value of first name in SHA256 (lower case).
     */
    hashed_first_name?: string
    /**
     * Hashed value of last name in SHA256 (lower case).
     */
    hashed_last_name?: string
    /**
     * Hashed value of phone in SHA256 (lower case).
     */
    hashed_phone?: string
    /**
     * Hashed value of address1 in SHA256 (lower case).
     */
    hashed_address1?: string
    /**
     * Hashed value of address2 in SHA256 (lower case).
     */
    hashed_address2?: string
    /**
     * Hashed value of city in SHA256 (lower case).
     */
    hashed_city?: string
    /**
     * Hashed value of zip in SHA256 (lower case).
     */
    hashed_zip?: string
    /**
     * Hashed value of country code in SHA256 (lower case).
     */
    hashed_country_code?: string
  }
  /**
   * The ID of the order placed on the originating platform.
   */
  source_identifier?: string
  /**
   * The source of the checkout.
   */
  source_name?: string
  /**
   * A valid URL to the original order on the originating surface.
   */
  source_url?: string
  /**
   * The price of the order in the shop currency after discounts but before shipping, duties, taxes, and tips.
   */
  subtotal_price?: string
  /**
   * Tags attached to the order, formatted as a string of comma-separated values. Tags are additional short descriptors, commonly used for filtering and searching. Each individual tag is limited to 40 characters in length.
   */
  tags?: string
  /**
   * Whether taxes are included in the order subtotal.
   */
  taxes_included?: boolean
  /**
   * The total discounts applied to the price of the order in the shop currency.
   */
  total_discounts?: string
  /**
   * The sum of all line item prices in the shop currency.
   */
  total_line_items_price?: string
  /**
   * The total outstanding amount of the order in the shop currency.
   */
  total_outstanding?: string
  /**
   * The sum of all line item prices, discounts, shipping, taxes, and tips in the shop currency. Must be positive.
   */
  total_price?: string
  /**
   * The sum of all line item prices, discounts, shipping, taxes, and tips in the shop currency in USD
   */
  total_price_usd?: string
  /**
   * The sum of all the taxes applied to the order in the shop currency. Must be positive.
   */
  total_tax?: string
  /**
   * The sum of all the tips in the order in the shop currency.
   */
  total_tip_received?: string
  /**
   * The ID of the user logged into Shopify POS who processed the order, if applicable.
   */
  user_id?: string
  /**
   * The date and time (ISO 8601 format) when the order was last modified.
   */
  updated_at?: string
  /**
   * Extra properties.
   */
  additional_fields?: {
    /**
     * Extra property name.
     */
    name?: string
    /**
     * Extra property value.
     */
    value?: string
  }[]
}
