// Generated file. DO NOT MODIFY IT BY HAND.

export interface Payload {
  /**
   * Unique event ID generated by Segment.
   */
  message_id: string
  /**
   * A unique identity and maintain user histories across sessions and devices under a single profile. If no identity is provided we will add the anonymous_id to the event. More on identify: https://developers.heap.io/docs/using-identify
   */
  identity?: string | null
  /**
   * The generated anonymous ID for the user.
   */
  anonymous_id?: string | null
  /**
   * Name of the user action. This only exists on track events. Limited to 1024 characters.
   */
  event?: string
  /**
   * An object with key-value properties you want associated with the event. Each key and property must either be a number or string with fewer than 1024 characters.
   */
  properties?: {
    [k: string]: unknown
  }
  /**
   * Defaults to the current time if not provided.
   */
  timestamp?: string | number
  /**
   * The type of call. Can be track, page, or screen.
   */
  type?: string
  /**
   * The name of the page or screen being viewed. This only exists for page and screen events.
   */
  name?: string
}
