import type { ActionDefinition } from '@segment/actions-core'
import type { Settings } from '../generated-types'
import type { Payload } from './generated-types'
import dayjs from '../../../lib/dayjs'
import { HEAP_SEGMENT_LIBRARY_NAME } from '../constants'
import { flat } from '../flat'
import { getUserIdentifier } from '../heapUtils'
import { IntegrationError } from '@segment/actions-core'

type HeapEvent = {
  event: string
  idempotency_key: string
  timestamp?: string
  properties?: {
    [k: string]: unknown
  }
  custom_properties?: {
    [k: string]: unknown
  }
  user_identifier?: {
    [k: string]: string
  }
}

type IntegrationsTrackPayload = {
  app_id: string
  events: Array<HeapEvent>
  library: string
}

const action: ActionDefinition<Settings, Payload> = {
  title: 'Track Event',
  description: 'Send an event to Heap.',
  defaultSubscription: 'type = "track"',
  fields: {
    message_id: {
      label: 'Message ID',
      type: 'string',
      description: 'Unique event ID generated by Segment.',
      required: true,
      default: {
        '@path': '$.messageId'
      }
    },
    identity: {
      label: 'Identity',
      type: 'string',
      allowNull: true,
      description:
        'An identity, typically corresponding to an existing user. If no such identity exists, we will set the anonymous id property on the user.'
    },
    anonymous_id: {
      label: 'Anonymous ID',
      type: 'string',
      allowNull: true,
      description: 'The generated anonymous ID for the user.',
      default: {
        '@path': '$.anonymousId'
      }
    },
    event: {
      label: 'Event Type',
      type: 'string',
      description: 'The name of the event. Limited to 1024 characters.',
      required: true,
      default: {
        '@path': '$.event'
      }
    },
    properties: {
      label: 'Event Properties',
      type: 'object',
      description:
        'An object with key-value properties you want associated with the event. Each key and property must either be a number or string with fewer than 1024 characters.',
      default: {
        '@path': '$.properties'
      }
    },
    timestamp: {
      label: 'Timestamp',
      type: 'datetime',
      description: 'Defaults to the current time if not provided.',
      default: {
        '@path': '$.timestamp'
      }
    },
    library_name: {
      label: 'Library Name',
      type: 'string',
      description: 'The name of the SDK used to send events',
      default: {
        '@path': '$.context.library.name'
      }
    }
  },
  perform: (request, { payload, settings }) => {
    if (!settings.appId) {
      throw new IntegrationError('Missing app ID')
    }

    if (!payload.anonymous_id && !payload.identity) {
      throw new IntegrationError('Either anonymous user id or identity should be specified.')
    }

    const standardProperties = { segment_library: payload.library_name || HEAP_SEGMENT_LIBRARY_NAME }
    const flattenedProperties = flat(payload.properties || {})
    const event: HeapEvent = {
      event: payload.event,
      custom_properties: flattenedProperties,
      properties: standardProperties,
      idempotency_key: payload.message_id
    }

    event.user_identifier = getUserIdentifier({ identity: payload.identity, anonymous_id: payload.anonymous_id })

    if (payload.timestamp && dayjs.utc(payload.timestamp).isValid()) {
      event.timestamp = dayjs.utc(payload.timestamp).toISOString()
    }

    const payLoad: IntegrationsTrackPayload = {
      app_id: settings.appId,
      events: [event],
      library: 'Segment'
    }

    return request('https://heapanalytics.com/api/integrations/track', {
      method: 'post',
      json: payLoad
    })
  }
}

export default action
