name: Test External

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-and-test:
    env:
      HUSKY: 0
      NX_DISABLE_DB: true
    runs-on: ubuntu-22.04

    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
