name: Track External PRs in Jira

on:
  pull_request_target:
    types: [opened]

jobs:
  create-jira:
    runs-on: ubuntu-latest
    name: Create a ticket in Jira to track the pull request
    if: github.event.pull_request.head.repo.fork
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: BE
          issuetype: Task
          summary: |
            External PR: ${{ github.event.pull_request.title }}
          description: |
            See: ${{ github.event.pull_request.html_url }}
          fields: '{"customfield_10002": "BE-132" }'

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
