name: release.yml
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create PR from'
        required: true
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Checkout branch
        run: |
          git checkout -b ${{ github.event.inputs.branch }}
          git push origin ${{ github.event.inputs.branch }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Build
        run: NODE_ENV=production yarn build

      - name: Version package
        run: yarn release

      - name: Create new PR
        run: |
          gh pr create --title "Release" --body "Release" --base main --head ${{ github.event.inputs.branch }}
