name: actions-release
on:
  push:
    branches:
      - new-prod-release-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Checkout branch
        run: |
          git checkout -b release-test
          git push origin release-test

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Build
        run: NODE_ENV=production yarn build

      - name: Version package
        run: yarn release

      - name: Create new PR
        run: |
          gh pr create --title "Publish" --body "Publish" --base main --head release-test
