name: Secret Keyword Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan-secrets:
    name: Scan for potential secrets
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45

      - name: Scan for suspicious keywords
        id: scan
        run: |
          echo "🔍 Scanning files for potential secrets..."
          suspicious_files=()
          pattern="(key|token|secret|password|code|auth)"
          exclude_pattern="oauth"

          for file in ${{ steps.changed_files.outputs.all_changed_files }}; do
            if [[ -f "$file" && $(file "$file" | grep -v 'binary') ]]; then
              matches=$(grep -iEn "$pattern" "$file" | grep -viE "$exclude_pattern" || true)
              if [[ -n "$matches" ]]; then
                suspicious_files+=("$file")
                echo "⚠️ Suspicious keywords found in $file:"
                echo "$matches"
                echo "$file" >> suspicious.txt
              fi
            fi
          done

          if [ ${#suspicious_files[@]} -eq 0 ]; then
            echo "✅ No suspicious keywords found."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - name: Add PR warning comment
        if: steps.scan.outputs.found == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: '⚠️ Potential Secret Keywords Detected'
          message: |
            🚨 **Warning:** Some files in this PR may contain sensitive keywords such as `key`, `token`, `secret`, `password`, `code`, or `auth`.

            Please verify that these values are **not hardcoded secrets**.
            Consider moving them to **GitHub Secrets** or environment configs.

            _Files flagged for review:_
            ```
            $(cat suspicious.txt)
            ```

      - name: Fail the workflow if suspicious keywords found
        if: steps.scan.outputs.found == 'true'
        run: |
          echo "❌ Potential secrets detected. Please review the PR before merging."
          exit 1
